Instance: ConsumerCOVIDRATResultQuestionnaireResponse
InstanceOf: QuestionnaireResponse
Description: "Example payload from an individual consumer reporting a COVID-19 rapid antigen test (RAT) result."
Usage: #example
* authored = "2024-03-24T21:48:20.520Z"
* item[0].linkId = "metaPhoneNumber"
* item[=].answer.valueString = "+64221234567"
* item[=].text = "Phone number"
* item[+].linkId = "extractPhoneNumberCode"
* item[=].answer.valueCoding = #8497 "Text patient com"
* item[+].item.linkId = "submit-modal-text"
* item[=].item.text = "The RAT result will be recorded against the official health record for Norma Griffiths."
* item[=].linkId = "submit-modal"
* item[=].text = "Enter result"
* item[+].item[0].linkId = "nlineModal-otherLines"
* item[=].item[=].text = "If your RAT has other lines or markings, consult the product information leaflet."
* item[=].item[+].linkId = "nlineModal-contactHealthline"
* item[=].item[=].text = "Contact Healthline for further information on 0800 358 5453."
* item[=].linkId = "nlineModal"
* item[=].text = "RATs with other lines"
* item[+].item.linkId = "highRiskModal-conditions"
* item[=].item.text = "List of conditions"
* item[=].linkId = "highRiskModal"
* item[=].text = "Other risk factors or medical conditions:"
* item[+].item.item[0].linkId = "reportResult-container-diagram"
* item[=].item.item[=].text = "A diagram showing what a positive COVID RAT Result looks like"
* item[=].item.item[+].linkId = "reportResult-container-controlLine"
* item[=].item.item[=].answer.valueBoolean = true
* item[=].item.item[=].text = "Is the control line (C) visible?"
* item[=].item.item[+].linkId = "reportResult-container-testLine"
* item[=].item.item[=].answer.valueBoolean = true
* item[=].item.item[=].text = "Is the test line (T) visible?"
* item[=].item.item[+].linkId = "reportResult-container-faintLines"
* item[=].item.item[=].text = "Faint lines"
* item[=].item.item[+].linkId = "reportResult-container-faintLinesDetail"
* item[=].item.item[=].text = "If a line is faint it should still be recorded as visible."
* item[=].item.item[+].linkId = "reportResult-container-nLineLink"
* item[=].item.item[=].text = "A small number of RATs have an ‘N’ line"
* item[=].item.item[+].linkId = "reportResult-container-testDate"
* item[=].item.item[=].answer.valueCoding = #2024-03-25 "Today"
* item[=].item.item[=].answer.valueCoding.code.extension.valueExpression.expression = "today()"
* item[=].item.item[=].answer.valueCoding.code.extension.valueExpression.language = #text/fhirpath
* item[=].item.item[=].answer.valueCoding.code.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-expression"
* item[=].item.item[=].text = "Day test was taken"
* item[=].item.item[+].linkId = "reportResult.container.onlyThisWeek"
* item[=].item.item[=].text = "You can only report a test taken within the last 7 days."
* item[=].item.linkId = "reportResult-container"
* item[=].linkId = "reportResult"
* item[=].text = "Report a COVID-19 Rapid Antigen Test (RAT) result"
* item[+].item.item[0].item[0].linkId = "aveSymptoms-container-intro-heading"
* item[=].item.item[=].item[=].text = "About these questions"
* item[=].item.item[=].item[+].linkId = "aveSymptoms-container-intro-text"
* item[=].item.item[=].item[=].text = "The following questions will give you an indication of whether you might be eligible to receive free oral COVID-19 antiviral medicine."
* item[=].item.item[=].linkId = "aveSymptoms-container-intro"
* item[=].item.item[+].item[0].linkId = "aveSymptoms-container-details-heading"
* item[=].item.item[=].item[=].text = "Symptoms of COVID-19 can include one or more of the following:"
* item[=].item.item[=].item[+].linkId = "aveSymptoms-container-details-list"
* item[=].item.item[=].item[=].text = "Sneezing and runny nose, sore throat, body aches, cough, feeling tired, headache, nausea and vomiting, diarrhoea, fever"
* item[=].item.item[=].item[+].linkId = "aveSymptoms-container-details-moreInfoHeading"
* item[=].item.item[=].item[=].text = "Visit this page for more information about COVID-19 symptoms:"
* item[=].item.item[=].item[+].linkId = "aveSymptoms-container-details-moreInfoLink"
* item[=].item.item[=].item[=].text = "COVID-19 symptoms"
* item[=].item.item[=].item[+].linkId = "aveSymptoms-container-details-hasSymptoms"
* item[=].item.item[=].item[=].answer.valueBoolean = true
* item[=].item.item[=].item[=].text = "Have you been experiencing any symptoms?"
* item[=].item.item[=].linkId = "aveSymptoms-container-details"
* item[=].item.item[+].linkId = "aveSymptoms-container-symptomDateHeading"
* item[=].item.item[=].text = "When did you start experiencing any of these symptoms?"
* item[=].item.item[+].linkId = "aveSymptoms-container-symptomDate"
* item[=].item.item[=].answer.valueCoding = #2024-03-22 "Friday, 22 March"
* item[=].item.item[=].answer.valueCoding.code.extension.valueExpression.expression = "today() - 3 days"
* item[=].item.item[=].answer.valueCoding.code.extension.valueExpression.language = #text/fhirpath
* item[=].item.item[=].answer.valueCoding.code.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-expression"
* item[=].item.item[=].answer.valueCoding.display.extension.valueExpression.expression = "(today() - 3 days).formatDate('dddd, D MMMM')"
* item[=].item.item[=].answer.valueCoding.display.extension.valueExpression.language = #text/fhirpath
* item[=].item.item[=].answer.valueCoding.display.extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-expression"
* item[=].item.item[=].text = "Select the date that your symptoms started"
* item[=].item.linkId = "aveSymptoms-container"
* item[=].linkId = "aveSymptoms"
* item[=].text = "Antiviral Eligibility"
* item[+].item.item[0].item[0].linkId = "aveCriteria-container-intro-heading"
* item[=].item.item[=].item[=].text = "About these questions"
* item[=].item.item[=].item[+].linkId = "aveCriteria-container-intro-text"
* item[=].item.item[=].item[=].text = "The following questions will give you an indication of whether you might be eligible to receive free oral COVID-19 antiviral medicine."
* item[=].item.item[=].linkId = "aveCriteria-container-intro"
* item[=].item.item[+].linkId = "aveCriteria-container-vulnerableText"
* item[=].item.item[=].text = "Eligible people include:"
* item[=].item.item[+].item.linkId = "aveCriteria-container-vulnerableContainer-isVulnerable"
* item[=].item.item[=].item.answer.valueBoolean = false
* item[=].item.item[=].item.text = "Do any of these apply to you?"
* item[=].item.item[=].linkId = "aveCriteria-container-vulnerableContainer"
* item[=].item.item[+].item[0].linkId = "aveCriteria-container-highRiskContainer-text"
* item[=].item.item[=].item[=].text = "These are some reasons you might be at high risk of becoming very sick from COVID-19:"
* item[=].item.item[=].item[+].linkId = "aveCriteria-container-highRiskContainer-isHighRisk"
* item[=].item.item[=].item[=].answer.valueBoolean = false
* item[=].item.item[=].item[=].text = "Do any of these apply to you?"
* item[=].item.item[=].linkId = "aveCriteria-container-highRiskContainer"
* item[=].item.linkId = "aveCriteria-container"
* item[=].linkId = "aveCriteria"
* item[=].text = "Antiviral Eligibility"
* item[+].item.item[0].item.linkId = "postSubmit-container-testResult-positive"
* item[=].item.item[=].item.text = "Result: Positive. COVID-19 was detected."
* item[=].item.item[=].linkId = "postSubmit-container-testResult"
* item[=].item.item[+].item[0].linkId = "postSubmit-container-eligibility-heading"
* item[=].item.item[=].item[=].text = "Antiviral eligibility"
* item[=].item.item[=].item[+].linkId = "postSubmit-container-eligibility-notEligible"
* item[=].item.item[=].item[=].text = "Not eligible"
* item[=].item.item[=].linkId = "postSubmit-container-eligibility"
* item[=].item.item[+].item[0].linkId = "postSubmit-container-isolation-heading"
* item[=].item.item[=].item[=].text = "Recommended isolation"
* item[=].item.item[=].item[+].linkId = "postSubmit-container-isolation-isolateFiveDays"
* item[=].item.item[=].item[=].text = "We recommend you stay home and isolate for five days from either the date you developed symptoms or the date you tested positive, whichever was earlier. You can leave your recommended isolation on the sixth day if you are feeling well."
* item[=].item.item[=].item[+].linkId = "postSubmit-container-isolation-stayAwayFromFacilities"
* item[=].item.item[=].item[=].text = "Recommended isolation"
* item[=].item.item[=].linkId = "postSubmit-container-isolation"
* item[=].item.item[+].item[0].linkId = "postSubmit-container-nextSteps-heading"
* item[=].item.item[=].item[=].text = "What to do next"
* item[=].item.item[=].item[+].linkId = "postSubmit-container-nextSteps-currentAdvicePositive"
* item[=].item.item[=].item[=].text = "Continue to follow current advice: https://info.health.nz/conditions-treatments/infectious-diseases/covid-19/if-you-have-covid-19/"
* item[=].item.item[=].linkId = "postSubmit-container-nextSteps"
* item[=].item.item[+].item[0].linkId = "postSubmit-container-furtherSupport-heading"
* item[=].item.item[=].item[=].text = "Further support"
* item[=].item.item[=].item[+].linkId = "postSubmit-container-furtherSupport-monitorSymptoms"
* item[=].item.item[=].item[=].text = "Monitor COVID-19 symptoms and if they get worse or you need medical care, call a healthcare provider or Healthline on 0800 358 5453."
* item[=].item.item[=].item[+].linkId = "postSubmit-container-furtherSupport-call111"
* item[=].item.item[=].item[=].text = "Call 111 if you find it difficult to breathe, pass out, or find it very difficult to wake up, are blue around the mouth, or very pale and cold, or are having severe chest pain."
* item[=].item.item[=].linkId = "postSubmit-container-furtherSupport"
* item[=].item.item[+].linkId = "postSubmit-container-exitComplete"
* item[=].item.item[=].text = "Exit"
* item[=].item.linkId = "postSubmit-container"
* item[=].linkId = "postSubmit"
* item[+].item[0].linkId = "extract-resultObservationValuePositive"
* item[=].item[=].answer.valueString = "DETECTED"
* item[=].item[=].text = "Extract - test result positive"
* item[=].item[+].linkId = "extract-resultObservationCode"
* item[=].item[=].answer.valueCoding = #XNZ5530 "SARS-CoV-2 RAT Self"
* item[=].item[+].item[0].linkId = "extract-diagnosticReport-code"
* item[=].item[=].item[=].answer.valueCoding = #XNZ5530 "SARS-CoV-2 RAT Self"
* item[=].item[=].item[+].linkId = "extract-diagnosticReport-identifierSystem"
* item[=].item[=].item[=].answer.valueString = "https://standards.digital.health.nz/ns/SendingApplication"
* item[=].item[=].item[+].linkId = "extract-diagnosticReport-identifierValue"
* item[=].item[=].item[=].answer.valueString = "RAT Catcher"
* item[=].item[=].item[+].linkId = "extract-diagnosticReport-result"
* item[=].item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-result) "SARS-CoV-2 RAT Self"
* item[=].item[=].item[+].linkId = "extract-diagnosticReport-phone"
* item[=].item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-phone) "Text patient com"
* item[=].item[=].item[+].linkId = "extract-diagnosticReportSubject"
* item[=].item[=].item[=].answer.valueBoolean = true
* item[=].item[=].item[+].linkId = "extract-diagnosticReportPerformer"
* item[=].item[=].item[=].answer.valueBoolean = true
* item[=].item[=].linkId = "extract-diagnosticReport"
* item[=].item[+].linkId = "subjectName"
* item[=].item[=].answer.valueString = "Norma Griffiths"
* item[=].item[=].text = "subject name"
* item[=].linkId = "extract"
* questionnaire = "https://build.fhir.org/ig/tewhatuora/cinc-fhir-ig/Questionnaire/ConsumerCOVIDRATResultQuestionnaire"
* author.identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* author.identifier.use = #official
* author.identifier.value = "ZZZ4640"
* author.display = "Norma Griffiths"
* author.type = "Patient"
* subject.identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* subject.identifier.use = #official
* subject.identifier.value = "ZZZ4640"
* subject.display = "Norma Griffiths"
* subject.type = "Patient"
* meta.lastUpdated = "2024-03-24T21:48:43.875Z"
* meta.versionId = "1"
* status = #completed