Instance: COVIDRATResultQuestionnaireResponse
InstanceOf: QuestionnaireResponse
Description: "Example payload from an aged residential care facility reporting a COVID-19 rapid antigen test (RAT) result."
Usage: #example
* authored = "2024-04-11T00:35:23.008Z"
* item[0].item.item[0].linkId = "p01-Consent-q01-1"
* item[=].item.item[=].text = "This report is confidential, and your/the patient's information will be kept safe in accordance with the New Zealand Privacy Act."
* item[=].item.item[+].linkId = "p01-Consent-q01-2"
* item[=].item.item[=].text = "When we collect your/the patient's information, we can only use it for the purposes for which it was collected.  For COVID RAT tests, this means we will only use the information to:"
* item[=].item.item[+].linkId = "p01-Consent-q01-3"
* item[=].item.item[=].text = "● Inform you about your/the patient's COVID-19 status"
* item[=].item.item[+].linkId = "p01-Consent-q01-4"
* item[=].item.item[=].text = "● Inform your/the patient's enrolled general practice team and general practitioner (where applicable)"
* item[=].item.item[+].linkId = "p01-Consent-q01-5"
* item[=].item.item[=].text = "● Ensure accurate national reporting of COVID-19 results and informing decisions regarding New Zealand’s response to COVID-19."
* item[=].item.item[+].linkId = "p01-Consent-q01-6"
* item[=].item.item[=].text = "● Perform anonymous statistical analysis and research purposes in line with usual processes and where permitted by the Privacy Act 2020 and Health Information Privacy Code 2020."
* item[=].item.item[+].linkId = "p01-Consent-q01-7"
* item[=].item.item[=].text = "We may need to share some of your/the patient's personal information with other agencies for health purposes and to ensure we meet our legal obligations."
* item[=].item.item[+].linkId = "p01-Consent-q01-8"
* item[=].item.item[=].text = "If you would like more information about how your/the patient's personal information is managed, please go to the Te Whatu Ora website, and look for our ‘privacy & security’ webpage."
* item[=].item.item[+].linkId = "p01-Consent-q01-9"
* item[=].item.item[=].text = "Do you wish to continue and consent to collection of your/the patient's information?"
* item[=].item.linkId = "p01-Consent-q01"
* item[=].item.text = "Consent to share information"
* item[=].linkId = "p01-Consent"
* item[=].text = "1. Consent"
* item[+].item[0].item.linkId = "p02-Test-Details-Role"
* item[=].item[=].item.answer.valueCoding.display = "Aged residential care"
* item[=].item[=].item.text = "What is your role?"
* item[=].item[=].linkId = "p02-Test-Details"
* item[=].item[+].item[0].linkId = "p02-Test-Kit-Batch"
* item[=].item[=].item[=].answer.valueString = "qwq"
* item[=].item[=].item[=].text = "Lot number"
* item[=].item[=].item[+].linkId = "p02-Test-Details-BatchCode"
* item[=].item[=].item[=].answer.valueCoding = #8499 "Lot Number"
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result"
* item[=].item[=].item[=].answer.valueCoding.display = "Detected"
* item[=].item[=].item[=].text = "Enter result"
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result-Positive"
* item[=].item[=].item[=].answer.valueString = "DETECTED"
* item[=].item[=].item[=].text = "Extract - test result positive"
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result-Code-Supervised"
* item[=].item[=].item[=].answer.valueCoding = #97097-0 "Supervised RAT SARS-CoV-2"
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result-PositiveNote"
* item[=].item[=].item[=].text = "The COVID-19 antigen was detected, which indicates the patient might be positive for COVID-19."
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result-Symptomatic"
* item[=].item[=].item[=].answer.valueBoolean = true
* item[=].item[=].item[=].text = "Is the patient presenting symptoms?"
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result-SymptomaticTrue"
* item[=].item[=].item[=].answer.valueBoolean = false
* item[=].item[=].item[=].text = "Extract - asymptomatic negative"
* item[=].item[=].item[+].linkId = "p02-Test-Kit-Result-SymptomaticCoding"
* item[=].item[=].item[=].answer.valueCoding = #84387000 "Asymptomatic"
* item[=].item[=].linkId = "p02-Test-Kit"
* item[=].item[=].text = "Covid test kit"
* item[=].item[+].item.linkId = "p02-Test-Date-Entry"
* item[=].item[=].item.answer.valueDate = "2024-04-11"
* item[=].item[=].item.text = "Day test was taken"
* item[=].item[=].linkId = "p02-Test-Date"
* item[=].linkId = "p02-Test"
* item[+].item[0].linkId = "p03-ExtractResources-DiagnosticReport-code-supervised"
* item[=].item[=].answer.valueCoding = #97097-0 "Supervised RAT SARS-CoV-2"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-identifierSystem"
* item[=].item[=].answer.valueString = "https://standards.digital.health.nz/ns/SendingApplication"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-identifierValue-RAT"
* item[=].item[=].answer.valueString = "RAT Catcher"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-result"
* item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-result) "SARS-CoV-2 RAT Self"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-batch"
* item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-batch) "Lot Number"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-asymptomatic"
* item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-asymptomatic) "Asymptomatic"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-authoriser"
* item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-authoriser) "Authoriser"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-site"
* item[=].item[=].answer.valueReference = Reference(urn:uuid:observation-site) "Specimen site"
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-subject"
* item[=].item[=].answer.valueBoolean = true
* item[=].item[+].linkId = "p03-ExtractResources-DiagnosticReport-performer"
* item[=].item[=].answer.valueBoolean = true
* item[=].item[+].linkId = "p03-ExtractResources-Observation-site"
* item[=].item[=].answer.valueString = "Nasal"
* item[=].item[+].linkId = "p03-ExtractResources-Observation-SiteCoding"
* item[=].item[=].answer.valueCoding = #66746-9 "Specimen site"
* item[=].item[+].linkId = "p03-ExtractResources-Observation-authoriser"
* item[=].item[=].answer.valueBoolean = true
* item[=].item[+].linkId = "p03-ExtractResources-Observation-authoriserCoding"
* item[=].item[=].answer.valueCoding = #8495 "RAT Authoriser"
* item[=].linkId = "p03-ExtractResources"
* questionnaire = "https://build.fhir.org/ig/tewhatuora/cinc-fhir-ig/Questionnaire/COVIDRATResultQuestionnaire"
* author.identifier.system = "https://standards.digital.health.nz/ns/hpi-person-id"
* author.identifier.use = #official
* author.display = " A name"
* author.type = "Practitioner"
* subject.identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* subject.identifier.use = #official
* subject.identifier.value = "ZAA0571"
* subject.display = "MASKED BALL"
* subject.type = "Patient"
* meta.lastUpdated = "2024-04-11T00:35:53.136Z"
* meta.versionId = "1"
* status = #completed