@startuml
'https://plantuml.com/sequence-diagram

autonumber "<b>[00]"

actor "Administrator" as admin
Participant "Appointment\nScheduling System" as s #LightSeaGreen
Participant "Shared Care\nFHIR Server" as fhir #palegreen
queue "NEMS" as n #gold
Participant "Appointment\nManagement System" as p #lightblue
actor "Patient/Administrator" as pat

title "Patient Arrives for Appointment"
p -> n: Subscribe to appointment-updated event
...

alt Patent arrived through Appointment Management System
    pat -> p ++ : Arrives for Appointment
    p -> fhir --++ : POST Encounter Resource (reference to Appointment)
    fhir -> s --++ : Create encounter for Appointment\nUpdate appointment status (arrived)
else Patent arrived through Appointment Scheduling System
    admin -> s : Confirms Appointment
end

s -> fhir --++ : Appointment Resource Updated
fhir -> n --++ : Publish appointment-updated event
n-> p -- : appointment-updated event notification
@enduml

