@startuml
'https://plantuml.com/sequence-diagram

autonumber "<b>[00]"

actor "Administrator" as admin

Participant "Appointment\nScheduling System" as s #LightSeaGreen
Participant "Shared Care\nFHIR Server" as fhir #palegreen
queue "NEMS" as n #gold
Participant "Appointment\nManagement System" as p #lightblue
actor "Administrator" as pat

title "Patient Departs Appointment"

p -> n: Subscribe to appointment-updated event
...

alt Patient departed through Appointment Management System
    pat -> p ++ : Departs from Appointment
    p -> fhir --++ : Update Encounter Resource (reference to Appointment)
    fhir -> s --++ : Update encounter for Appointment\nUpdate appointment status (fulfilled)
else Patient departed through Appointment Scheduling System
    admin -> s : Departs patient from Appointment
end

s --> fhir --++ : Appointment Resource Updated

fhir -> n --++ : publish appointment-updated event
n-> p -- : appointment-updated event notification

@enduml

