@startuml
'https://plantuml.com/sequence-diagram

autonumber "<b>[00]"

actor "Administrator" as admin
Participant "Patient Administration System\n(PAS)" as pas #LightSeaGreen
Participant "Appointment FHIR\nInterface" as fhir #palegreen
queue "NEMS" as n #gold
Participant "Appointment\nManagement System" as p #lightblue

title "Retrieve Patient Demographics"
p -> n: Subscribe to patient-updated event
...

admin -> pas ++ : Patient details updated

pas -> n --++ : Publish patient-updated event
n-> p --++ : patient-updated event notification


p -> fhir ++: Get Patient Resource (by NHI)
fhir -> pas ++: Retrieve patient demographics
return Patient demographics
return Patient Resource

@enduml