@startuml
'https://plantuml.com/sequence-diagram

autonumber "<b>[00]"
Participant "PQMS\nPatient Queue\nManagement System" as p #dodgerblue/lightskyblue
Boundary "API\nGateway" as a #gold
Collections "Middleware\nIntegration\nPlatform" as m #palegreen/whitesmoke
Database "SIPICS\nPatient\nAdministration\nSystem (PAS)" as s #LightSeaGreen/yellow
Database "Cardiobase\nCardiology\nInformation\nSystem" as c #red/orange
Participant "FHIR\nConverter\nService" as f #royalblue/white
Database "FHIR CDR" as w #tomato/yellow
Participant "NEMS\nNational Event\nManagement Service" as n #lightblue

title Update Appointment (FHIR REST API)
p -> a: FHIR API\nUpdate Appointment
a -> m++ #palegreen: FHIR Routed\nUpdate Appointment
alt#Gold #lightblue Destination SIPICS
  m -> m: <font color=blue>Mapping FHIR\n<font color=blue>to SIPICS API
  m -> s: Appointment status\nupdate via SIPICS API
  s -> f: Appointments\nHL7 v2 SIU/ADT
  f -> w: FHIR updates
  f --> s: Response
  s --> m: Response
  m --> m: <font color=blue>Mapping SIPICS\n<font color=blue>response to FHIR
else #Pink Destination Cardiobase
  m -> m: <font color=blue>Mapping FHIR\n<font color=blue>to HL7v2
  m -> c: Appointment Status\nupdate HL7v2 ORM
  c -> f: Appointments\nHL7 v2 SIU/ADT
  f -> w: FHIR updates
  f --> c: Response
  s --> m: Response
  m --> m: <font color=blue>Mapping Cardiobase\n<font color=blue>response to FHIR
end
return FHIR Success
a->p: FHIR Routed\nPatient Resource



w -> n: Update event\ntrigger
n -> p: Update event




@enduml

