@startuml
'https://plantuml.com/sequence-diagram

autonumber "<b>[00]"

actor "Booking Administrator" as admin
Participant "Appointment\nScheduling System" as s #LightSeaGreen
Participant "Shared Care\nFHIR Server" as fhir #palegreen
queue "NEMS" as n #gold
Participant "Appointment\nManagement System" as p #lightblue

title "Appointment Created/Updated"
p -> n: Subscribe to appointment-updated event
...
admin -> s ++ : Book appointment

s -> fhir --++ : Appointment Resource Created/Updated

fhir -> n --++ : publish appointment-updated event
n-> p --: appointment-updated event notification

p -> fhir ++ : Get Appointment
return Appointment Resource
@enduml

