@startuml FHIR-resource-careplan-rheumaticfever-pilot
'!include plantuml-include/std-skinparams-classdiagram.iuml

top to bottom direction
scale 800 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #RoyalBlue   
skinparam ArrowFontColor #RoyalBlue   
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment right
skinparam BoxPadding 10
skinparam ClassFontSize 16
skinparam ClassFontStyle bold
skinparam dpi 300
skinparam FooterFontSize 14
skinparam FooterFontStyle italic
skinparam LegendBackgroundColor #Snow
skinparam LegendFontName Helvetica
skinparam LegendFontSize 16
skinparam linetype ortho
skinparam nodesep 60
skinparam NoteBackgroundColor #LightYellow
skinparam NoteFontSize 15
skinparam NoteTextAlignment left
skinparam ranksep 60
skinparam roundcorner 5
skinparam TitleFontSize 20

title "Rheumatic fever FHIR resources (pilot phase)"

frame "Rheumatic fever bounded context - FHIR resource types" as HNZMain {

  ' class "AllergyIntolerance" as Allergy #LightSalmon ##[bold] {
  '   Represents a patient allergy or
  '   intolerance relating to R/F
  '   penicillin medications.
  '   ----
  '   +code: SNOMED
  '   +category: SNOMED
  '   +reference: subject (patient)
  '   +reference: asserter (source)
  '   +complex[]: reaction
  '
  ' }
  
  class ":Appointment" as APPT <<APPOINTMENT>> #GhostWhite ##[bold] {
    Appointments in which preventative 
    (prophylactic) medication is administered.
    ----
    * text "Secondary prophylaxis appointment"
    * status: ""#booked | #arrived""
    * start: instant (UTC)
    * end: instance (UTC)
    * participant: Reference(Practitioner)
  }


  class ":RheumaticFeverCarePlan" as CP <<CAREPLAN>> #LightSalmon ##[bold] {
    Profiles FHIR CarePlan so it can act as 
    registration for rheumatic fever patients. 
    ---
    *identifier[NHI] (official): NHI
    *identifier[case] (usual): case Id (salesforce)
    ---
    * title "Rheumatic fever care plan for patient X"
    * status: ""#active"" etc.
    * period: date range
    * category: SNOMED ""#tbc"" "RF secondary prevention care plan"
    * intent: ""#Plan"" etc.
    * activity[]: 
      \tReference(MedicationRequest or Appointment) **only**
    -- extensions --
      + **onHoldReason**: string
      + **closureReason**: string
  }

  class ":RheumaticFeverPatient" as RfPatient <<NZPATIENT>> #LightSalmon ##[bold] {
    Profiles NzPatient so it can define
    whanau care team members as contacts 
    ---
    *identifier[NHI] (official): NHI
    ---
    *name: HumanName
    *birthDate: date
    *communication.language
    *gender: code
    *deceasedBoolean: boolean
    *telecom: ContactPoint[]
    *address: Address[]
    +iwi: code
    +ethnicity 0..*: code[]
    +nzCitizen: code
    .. (extensions)..
    +**patient.contact[].**
      \t **whanauMemberCareRole**: Coding
      \t **whanauMemberCareRelationship**: string
      \t **whanauMemberCarePrimary**: boolean
    +**interpreterRequired**: boolean
  }

  class ":**RheumaticFeverCareTeam" as CareTeam <<CARETEAM>> #LightSalmon ##[bold] {
    Profiles CareTeam to categorize only.
    Identifies practitioners/providers
    involved in patient's care 
      (performing RF secondary prevention)
    ---
    * category: 
      <size:12>""| **Secondary Prophylaxis Team**""
    * participant[].role
  }

  class ":Consent^\ndata collection" as Consent <<CONSENT>> #GhostWhite ##[bold] {
      Represents a patient's active or
      provisional consent to RF Services 
      collection and use of data.
      ----
      * status: ""#proposed | active"" 
      * scope: ""#patient-privacy""
      * dateTime: date
      * period: date range
      * policy: uri
  }


  class ":RheumaticFeverCondition" as Condition <<NZCONDITION>> #LightSalmon ##[bold] {
    Profiles NzCondition (NZ Base) for RF 'case' details.
    ---
    * identifier (usual): {{salesforce diagnosis Id}}
    ---
     * code: SNOMED diagnosis code
     * severity: ""#mild | #moderate | #severe""
     * clinicalStatus: #active etc.
     * recordedDate: date
    -- extensions --
      * **rhdSeverity**: code (dedicated ValueSet)
      * **diagnosticCertainty**: code (dedicated ValueSet)
  }

  class ":Medication" as MED <<MEDICATION>> #GhostWhite ##[bold] {
    * code: SNOMED (brand)
    * ingredient: SNOMED (type)
  }

  class ":MedicationRequest" as MEDREQ <<NZMEDICATIONREQUEST>> #GhostWhite ##[bold] {
    Medication that is planned for RF prevention
    ---
    *status: code //medicationRequestStatus//
    *intent: ""#plan""
    *authoredOn: dateTime
    *validityPeriod: dateTime
    * dosageInstruction:
      \troute: SNOMED
      \tsite: SNOMED
      \tdoseAndRate
      \tadditionalInstruction: SNOMED [frequency]
  }

  
  class ":MedicationStatement" as MEDSTMT <<NZMEDICATIONSTATEMENT>> #GhostWhite  ##[bold] {
    Detail of benzathine etc.
    actually administered
    --
    status: ""#completed""
    code: NZMT
    note: brand of benzathine used
  }

  class ":MedicationStatement" as CONTMEDSTMT <<NZMEDICATIONSTATEMENT>> #GhostWhite  ##[bold] {
    Strength of lignocaine 
    administered for pain relief
    --
    medicationCodeableConcept: NZMT
  }


  class ":Questionnaire\n(definitional)" as Questionnaire <<QUESTIONNAIRE>> #OrangeRed {
    Four canonical instances defined by Te Whatu Ora
    1 ""Patient Medication Allergies""
    2 ""Medications and Follow-up Guidance""
    3 ""Patient & Whanau Goals and Preferences""
    4 ""Secondary Prophylaxis Health Assessment""
  }

  class ":QuestionnaireResponse" as QR <<QUESTIONNAIRERESPONSE>> #GhostWhite ##[bold] {
    Collects form data items
    as defined by a Questionnaire
    ----
    * value[x]: item[].answer
  }

  ' class ":DiagnosticReport" as DIAG #GhostWhite ##[bold] {
  '   * status: ..
  '   * code: SNOMED..
  '   ...
  '   Any diagnosis 
  '    detail as required
  '   ...
  '   +category
  ' }

  ' note as DiagNote #Yellow
  '   DiagnosticReport may be 
  '   used in future to capture
  '   diagnosis detail.
  ' end note
  ' DiagNote .l. Condition

  class ":Encounter" as Encounter <<ENCOUNTER>> #GhostWhite ##[bold] {
    Tracks patient's secondary 
    prophylaxis appointment.
    ---
    * class: ""#AMB"" "ambulatory"
    * status: ""#planned | #finished""
    * participant[]: Reference[Patient, Practitioner]
    * period: datetime range
    * location: Reference[HPI facility]
  }
}

frame "Te Whatu Ora national systems" as National {

  class "RFCCS (Salesforce)" as RFCCS <<external data>> #SkyBlue {
    Salesforce logical resource
    ---
    * logical id: CarePlanId
  }

  class "Episurv" as EPISURV <<external data>> #SkyBlue {
    Notifiable disease surveillance
    ---
    * logical id: Episurv number
  }

}

frame "Te Whatu Ora NHI/HPI" as NationalIdentifier {

  class "Patient (NHI)" as Patient <<logical resource>> #SkyBlue {
    * logical id: NHI
  }

  class "HPI" as HPI <<logical resource>> #SkyBlue {
    logical identifier formats:
    + ""NNXXXX"" - 
      \tpractitioner CPNs
    + ""GXXNNN-C""
      \tHPI Org Id - orgs
    + ""FXXNNN-C""
      \tHPI Facility Id - locs
  }

  Patient -[hidden]d- HPI

}

' ********
' * Entities outside any frame are in other bounded contexts

class "RelatedPerson" as Related <<logical resource>> #SkyBlue {
  * logical id: name
}



class "NZMT terminology" as NZMT <<logical resource>> #SkyBlue {
  * medication coding
}

' ********
' plantuml positioning

' ********
' * resource linkages

APPT "supportingInformation\n<size:18>1" -- "appointment\n<size:18>1" Encounter: <>

'Condition "1" - "1" DIAG: > "stage.\nassessment"

CP "addresses" -[#SlateGray]u-{ Condition : >
CP "supportingInfo" }--{ "basedOn" QR: <>
CP "subject" - "1" RfPatient
CP "activity.\nreference" -[#SlateGray,thickness=4]d---{ "basedOn" MEDREQ: >
CP "<color:RoyalBlue>**Identifier[NationalSystem]**" .[#SkyBlue]u. "1" RFCCS : > "<color:RoyalBlue>Salesforce care plan Id"
CP "careTeam" ---{ CareTeam
CP " activity.\nreference" -[#SlateGray,thickness=4]l-{ APPT: >
CP "author" }.[#SkyBlue,dashed]. HPI : > ""CarePlan.**author**"" \nidentifies Lead Provider

CareTeam "participant.member" }.[#SkyBlue,norank].{ HPI
CareTeam "participant.member" }.[#SkyBlue]..{ Related

Condition .[#SkyBlue]. "1" Patient : > subject
Condition "<color:RoyalBlue>**Identifier[NationalSystem]**" .[#SkyBlue]u. "1" EPISURV : > "<color:RoyalBlue>Episurv number"

Consent "patient" .[#SkyBlue]. "1" Patient : >
Consent "performer" .[#SkyBlue,norank]. "1" HPI : >

'DIAG "basedOn" }-- CP

Encounter .[#SkyBlue,norank]. "1" HPI: > "participant,\nserviceProvider" 

MEDREQ "medication[x]" }-d- "1" MED : >
MEDREQ "requester" .[#SkyBlue,norank]. "1" HPI
MEDREQ "subject" .[#SkyBlue,norank]. "1" Patient


MEDSTMT -l-* "partOf" CONTMEDSTMT: <
MEDSTMT "1" -l- "1" Encounter: > context
MEDSTMT "basedOn" }- MEDREQ : >
MEDSTMT "medication\nReference" }--"1" MED: > 

MED "code\ningredient" .[#SkyBlue]d- NZMT
CONTMEDSTMT "lignocaine\nconcentration\ncoding".[#SkyBlue,norank]d- NZMT

RfPatient "Identifier[NHI]" .[#SkyBlue]r. "1" Patient

QR "encounter" --> Encounter
QR "<color:Red>questionnaire" }.[#Red]l.. Questionnaire: > \n\n\n\n

legend left
  **Notes**
  - Model of data types (FHIR resources) and relations (FHIR references) for national rheumatic fever FHIR data.
  - Arrows show direction of FHIR reference.
  - Solid/open dots indicate mandatory/optional data elements.

  **Key to datatype colours**
  |= colour |= stereotype |
  | <back:#GhostWhite>ghost white\n | Standard FHIR resource in TWO Shared Care API |
  | <back:#LightSalmon>salmon\n | Profiled FHIR resource |
  | <back:#OrangeRed>orange red\n | Canonical shared resource defined by TWO |
  | <back:#SkyBlue>sky blue\n| Logical identifier reference to records in other national systems |
endlegend

@enduml