@startuml flow-FHIR-rheumaticfever-lifecycle

title "Typical sequence of rheumatic fever FHIR resource instance creation"

skinparam dpi 400
scale 400 width

skinparam BoxPadding 10
skinparam ParticipantPadding 5
skinparam roundcorner 2
skinparam sequenceArrowThickness 2
skinparam TitleFontSize 20

[*] -d-> P : Patient not registered /no FHIR records.
[*] ---> CP : Patient has an existing FHIR representation.

state "patient registration" as REGO #FloralWhite {
  
  state "NzPatient created/updated" as P {
    state NzPatient #LightGray
  }

  state "**CarePlan** created" as CP {
    state CarePlan #Red
    state Condition #LimeGreen
  }

  state "**Consent** created and linked" as CONSENT {
    state Consent #Orange
  }

  state "CarePlan --> **#draft**" as REG_COMPLETE #Red ##[bold]
  

  P -r-> CP : ok
  CP -d-> CONSENT : ok
  CONSENT -l-> REG_COMPLETE : ok

}

note right of REG_COMPLETE 
  On registration, CarePlan moves into **#draft** state.
  Other sector health applications can interpret from this 
  that a patient is "registered" with an NZ RF Secondary 
  Prevention Service.
endnote

state SETUP <<fork>>

REG_COMPLETE -d-> SETUP

state "care plan setup" as SETUP #FloralWhite {

  state "Initial diagnosis completed" as DIAG {
    state "Condition (updated)" #LimeGreen
  }

  state "CareTeam defined" as CARETEAM {
    state CareTeam #LightSalmon
  }
  state "Allergies recorded" as ALLERGY {
    state "Questionnaire type A\nResponse" #SkyBlue
  }

  state "Medications & Follow-up\nGuidance captured" as FOLLOW {
    state "Questionnaire type B\nResponse" #SkyBlue
  }
  
  state "Patient / Whanau \n Goals & Prefs\n recorded" as GOALS {
    state "Questionnaire type C\nResponse" #SkyBlue
  }

  SETUP --> DIAG
  SETUP --> CARETEAM
  SETUP --> ALLERGY
  SETUP --> FOLLOW  
  SETUP --> GOALS

  state ALLSETUP <<join>>
  
  DIAG -d-> ALLSETUP
  CARETEAM --> ALLSETUP
  ALLERGY --> ALLSETUP
  FOLLOW --> ALLSETUP
  GOALS --> ALLSETUP

  note right of ALLSETUP 
    when all parts ready
  end note

}

state "CarePlan --> **#active**" as CPA #Red

ALLSETUP -d-> CPA

CPA --> MEDPLAN

state "Medication planning" as MEDPLAN #FloralWhite  {
  state "Plan a period of medication (say **2023**)" as MEDREQUEST {
    state "Medication\nRequest 2023" as MR #MediumPurple
    state "Medication (Benzathine)" #CadetBlue
    note bottom of MR
      SP medication frequency 
      is set (say every 28 days)
    end note
  }

  state "Book appointments" as ACT2 {
    state "Appointment \n(planned encounter)\n July 11\n**#booked**" as AP1 #OrangeRed
    state "Appointment \n(planned encounter)\n August 8 2023\n**#booked**" as AP2 #OrangeRed
    state "Appointment \n(planned encounter)\n Sept. 5 2023\n**#booked**" as AP3 #OrangeRed
    state "more appointments..." as AP4 #OrangeRed
  }

  state "MedicationRequest --> **#active** \n& appointments planned" as PLANDONE #White/MediumPurple

  note left of PLANDONE
    When medication planned
    for a sufficient period
  end note

  state "CarePlan --> **#active**" as CPA #Red

  MEDREQUEST --> ACT2
  ACT2 -d-> PLANDONE
}

PLANDONE --> APPOINTMENTS

state "Secondary prophylaxis activity recording" as APPOINTMENTS #FloralWhite {
  state "First appointment data capture (say **August 2023**)" as APPT1 {
    state "Medication\nStatement (aug)" #PaleGreen
    state "Questionnaire type D\nResponse (aug)" #SkyBlue
    state "Encounter of\n aug appointment" #Yellow
    state "Appointment (aug)\n --> **#fulfilled**" #OrangeRed
  }

  state "Second appointment data capture (say **September 2023**)" as APPT2 {
    state "Medication\nStatement (sept)" #PaleGreen
    state "Questionnaire type D\nResponse (sept)" #SkyBlue
    state "Encounter of\n sept appointment" #Yellow
    state "Appointment (sept)\n--> **#fulfilled**" #OrangeRed
  }

  APPT1 --> APPT2

  state "Similar further instance sets ..." as APPTX {
  }

  note left of APPTX 
    FHIR resources accumulate
    as rheumatic fever patient
    care continues.
  end note

  APPT2 -d-> APPTX
}

state "ongoing care coordination" as ONGOING #FloralWhite {
  state "CarePlan **#active**" as CPA2 #Red ##[bold]
  state "CarePlan **#on-hold**" as CPH #Red ##[bold]
  state "CarePlan cancelled (**#revoked**)" as CPR #Red ##[bold]
  state "CarePlan closed (**#completed**)" as CPC #Red ##[bold]
}
APPTX -d-> CPA2

CPA2 -> CPH
CPA2 <- CPH
CPA2 -d-> CPC
CPH ---> CPR
CPR --> [*]
CPC --> [*]

footer "Health NZ/Te Whatu Ora.  Generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml
