@startuml "ManaakiNgaTahiMeasurementsExample"

actor Patient #Tan
participant "Patient Portal" as PP
actor Practitioner #Tan
participant "Practice Management\nStoftware" as PMS
boundary "Manaaki Nga Tahi\nFHIR API" as API

Patient -> Practitioner : Patient visits practitioner
Practitioner <-> API : Look up patient details
Practitioner -> Patient : Consultation
Practitioner -> Practitioner : Determines measurements required
Practitioner -> Patient : Discuss consent to capture and record measurements
Practitioner -> PMS
PMS -> API : Record consent (Consent)
Practitioner <-> Patient : Take measurements (Pule, temp etc.)
Practitioner -> PMS : Record measurements
PMS -> API : Record measurements (Observation)
... Some time passes ...
Patient -> PP : View measurements
PP -> API : Retrieve measurements (Observation)
PP -> Patient : Display historical measurements

@enduml