@startuml obj-FHIR-data-rheumaticfever-appointment

title "Rheumatic fever -- secondary prophylaxis medication planning and appointment recording"

left to right direction
'skinparam dpi 200
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 60
skinparam roundcorner 5
skinparam sequenceArrowThickness 2
skinparam TitleFontSize 20

caption FHIR resource instances object model

!procedure $Coding($Alias,$System,$Code,$Display)
  object "<color:GhostWhite>$System" as $Alias #MediumPurple {
    <color:GhostWhite><size:11>**$Code**-$Display
  }
!endprocedure

!procedure $ObjectDiagramLegendWithNote($heading,$noteline)

  legend bottom
    **$heading**
    $noteline
  endlegend

!endprocedure

' Codesystems defined by others
package "Medication definition" as CODING {
  $Coding(MedCoding,"medication ingredient","NZMT ..6105","benzathine penicillin")
  $Coding(MedCoding,"medication ingredient","NZMT ..6107","amoxicillin")
  $Coding(MedCoding,"medication ingredient","NZMT ..6109","penicillin VK")
  $Coding(MedCoding,"medication ingredient","NZMT ..6100","erythromycin")

  $Coding(MedBrand,"Benzathine brand","NZMT ..6108","Bicillin L-A")
  $Coding(MedBrand,"Benzathine brand","NZMT tbc","Tardocillin")
  $Coding(MedBrand,"Benzathine brand","NZMT tbc","Lentocillin")

  $Coding(Route,"Med. route","SNOMED..1000","Intramuscular route")
  $Coding(Route,"Med. route","SNOMED..3006","Oral route")

  $Coding(Site,"Med. site","SNOMED..10101","Left ventrogluteal ..")
  $Coding(Site,"Med. site","...","etc.")

  object ":**Medication**" as MED <<Medication>> #SkyBlue {
    Planned secondary prophylaxis medication brand and ingredient
  }

  'MedCoding -[hidden]d- MedBrand
  MedBrand -[hidden]d- MED
  MED -[hidden]d- Route
  Route -[hidden]r- Site

  MED "code" -[#MediumPurple,norank]> MedCoding
  MED "\ningredient" -[#MediumPurple,norank]d-> MedBrand
}

frame "Planning and recording of secondary prophylaxis medication activity" as HNZFHIRREPO #Snow {
  
  object "<size:16>:RheumaticFeverCarePlan" as CP <<CarePlan>> #OrangeRed {
    Each CarePlan defines a list
    of planned and completed 
    activities ...
  }

  package """<CarePlan.activity[].reference>""" as Activities #White/SkyBlue { 
    
    'object "secondary prophylaxis\nmedication planning" as PLAN_BENZA_2023 #LightSalmon
  
    object "<size:15>:**RheumaticFeverMedicationRequest**" as MR1 <<MedicationRequest>> #MediumPurple {
      * text: "Benzathine medication plan 2023"
      * status: //**#active**//
      * intent: //#plan//
      * dosageInstruction
        \t-route:SNOMED
        \t-site:SNOMED
        \t-additionalInstruction [frequency]
        \t-doseAndRate:Dosage
      * performer: Ref(Practitioner)
      * validityPeriod: eg. **2023-01 to 2023-12**
      --- extension ---
      * medicationFrequency: **Every twenty eight days**
    }

    ' completed appointments    
    object "<size:16>July2023:**Appointment**" as JULY_APPT #LightYellow {
      *identifier[case] (usual): case Id (salesforce)
      ---
      * status: //**#fulfilled**//
      * start: **2023-07-11**
      * supportingInfo: service provider Ref(HPI org)
      * participant: Reference(Practitioner)
    }

    object "<size:16>August2023:**Appointment**" as AUGUST_APPT #PaleGoldenRod {
      *identifier: type #CarePlanActivityId (SF)
      ---
      * status: //**#fulfilled**//
      * start: **2023-08-08**
      * supportingInfo: service provider Ref(HPI org)
      * participant: Reference(Practitioner)
    }
    
    ' planned appointment
    object "<size:14>September2023:**Appointment**" as SEPTEMBER_APPT #pink {
      *identifier: type #CarePlanActivityId (SF)
      ---
      * status: //**#booked**//
      * start: **2023-09-05**
      * supportingInfo: service provider Ref(HPI org)
      * participant: Reference(Practitioner)
    }

    object "<size:14>October2023:**Appointment**" as OCTOBER_APPT #pink {
      *identifier: type #CarePlanActivityId (SF)
      ---
      * status: //**#booked**//
      * start: **2023-10-03**
      * supportingInfo: service provider Ref(HPI org)
      * participant: Reference(Practitioner)
    }

    'arrange activities in line
    AUGUST_APPT -[hidden]r- MR1
    MR1 -[hidden]r- JULY_APPT
    SEPTEMBER_APPT -[hidden]r- OCTOBER_APPT
    OCTOBER_APPT -[hidden]r- SEPTEMBER_APPT
  }

  package "July 2023 completed appointment detail" as JULY #FloralWhite/LightYellow {
  
    object "<size:14>july2023:Encounter" as EInj2 #Yellow {
      * status: //**#finished**//
      * period: 2023-07-11
      * participant: Ref(Practitioner)
      * serviceProvider: Ref(Organisation)
    }

    object "<size:14>:MedicationStatement\n(Benzathine)" as MEDSTMT2 #LightGreen {
      * status: //**#completed**//
      * effectiveDateTime: 2023-07-11
      * dosage: Dosage 
          // actual dose quantity,site,route
    }

    object "<size:14>:QuestionnaireResponse\n(health assessment)" as QR2 #SkyBlue {
      * questionnaire: Canonical(SPHA)
      * status: //**#completed**//
      * authored: 2023-07-11
      * item.*: responses
    }

    
    EInj2 <-[norank]r- MEDSTMT2: < context
    ' MEDSTMT2 -[#Gray]-* MEDSTMT2: <size:10>Lignocaine (contained)\n<size:10>MedicationStatement
    ' MEDSTMT2 "derivedFrom" -d-> QR2
    QR2 "encounter" -[norank]--> EInj2 
  }

  package "August 2023 completed appointment detail" as AUGUST #PaleGoldenRod/FloralWhite {

    object "<size:14>august2023:Encounter" as EInj1 #yellow {
      * status: //**#finished**//
      * period: 2023-08-08
      * participant: Ref(Practitioner)
      * serviceProvider: Ref(Organisation)
    }

    object "<size:14>:MedicationStatement\n(Benzathine)" as MEDSTMT1 #LightGreen {
      * status: //**#completed**//
      * effectiveDateTime: 2023-08-08
      * dosage: Dosage 
        // actual dose quantity,site,route
    }

    object "<size:14>:QuestionnaireResponse\n(health assessment)" as QR1 #SkyBlue {
      * questionnaire: Canonical(SPHA)
      * status: //**#completed**//
      * authored: 2023-08-08
      * item.*: responses
    }

    EInj1 <-[norank]l- MEDSTMT1: < context
    ' MEDSTMT1 -[#Gray,norank]-* MEDSTMT1: <size:10>Lignocaine (contained)\n<size:10>MedicationStatement
    ' MEDSTMT1 "derivedFrom" -d-> QR1
    QR1 "encounter" -[norank]r-> EInj1
  }

  ' positioning

  ' connectors
  CP "activity" *-u-> Activities

  JULY_APPT "supportingInfo" -u-> EInj2
  EInj2 "appointment" -[thickness=3,norank]-> JULY_APPT

  AUGUST_APPT "supportingInfo" -d-> EInj1
  EInj1 "appointment" -[thickness=3,norank]-> AUGUST_APPT

  MR1 "medication[x]\n<size:14>1" -[norank]-> "1" MED
  MR1 "<color:MediumPurple><size:14>route" .[#MediumPurple,dotted,norank].> Route
  MR1 "<color:MediumPurple><size:14>site" .[#MediumPurple,dotted,norank].> Site

  MEDSTMT1 "basedOn" -[thickness=3,norank]--> MR1
  MEDSTMT2 "basedOn" -[thickness=3,norank]--> MR1

  MEDSTMT1 -[norank]u-> MED : > medicationReference
  MEDSTMT2 "medication\nReference" -[norank]> MED 

  'notes
  note as N1
    These three instances, added to the
      original Appointment instance, capture
      detail from a **completed**
      secondary prophylaxis appointment:
    - **Encounter** the who / what / where etc.
    - **MedicationStatement** the actual meds given
    - **QuestionnaireResponse** health assessment
  end note

  N1 .u. JULY

  note as N2
    Before attendance Appointments in #booked
      status represent the planned patient
      visits for secondary prophylaxis medication.
      Each appointment identifies the nurse who
      is planned to see the patient as a 
      participant in the appointment.   
      
      After the appointment is attended, its 
      status will update to #fulfilled and
      medication administered and other details 
      from the encounter will be captured in 
      additional FHIR resource instances as
      shown above.
  end note

  N2 .. SEPTEMBER_APPT

}

legend bottom
  **Legend**
  1) Arrows indicate direction of FHIR reference
  2) Object colour shading reflects colours used in //Data Dictionary// mapping.
endlegend


@enduml