@startuml obj-FHIR-data-consent-givenonbehalf

top to bottom direction
skinparam dpi 300
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam roundcorner 5
skinparam sequenceArrowThickness 2

caption FHIR instance data model - patient consent given on-behalf by related person scenario

!procedure $Coding($Alias,$System,$Code,$Display)
  object "<color:GhostWhite>$System" as $Alias #MediumPurple {
    <color:GhostWhite><size:11>**$Code**-$Display
  }
!endprocedure

!procedure $ObjectDiagramLegendWithNote($heading,$noteline)

  legend bottom
    **$heading**
    $noteline
  endlegend

!endprocedure


frame "HNZ FHIR API resources under management" as HNZMain {

  package "<size:12>active patient consent given on-behalf" as ACTIVE #Snow {
      
    object "activeConsentExample\n<size:16>**:Consent**" as CONSENT #GhostWhite/LightCoral {
      * status: ""**#active**""
      * scope: ""**#patient-privacy**""
      * dateTime: ""2023-01-21""
      * policy: reference to NZ Privacy Act / HIPC
    }

    object "data access provision:\n<size:15>Consent**.provision**" as DAP #GhostWhite {
      * type: ""#permit""
      * period: ""2023-01-21 to ..""
    }

    object "person giving consent\n<size:15>**RelatedPerson**" as RP #GhostWhite {
      * name.given: Beryl
      * name.family: Hackett
      * relationship: ""#PRN""
    }


  }

  object "privacy questions\n<size:15>**:Questionnaire**" as Q #Red

  package "<size:12>All resource instances protected by this consent" {
    rectangle COVERED {
      object "patient's responses\n<size:14>**:QuestionnaireResponse**" as QRC #LightSalmon
      object "resource x<sub>1</sub>\n**<size:15>:X**" as AnyResource #LightGray
      object "resource y<sub>1</sub>\n**<size:15>:Y**" as AnotherResource #LightGray
    }
    QRC -[hidden]d- AnyResource
    AnyResource -[hidden]d- AnotherResource
  }

  ' connectors
  'DAP "1" -[thickness=3,#RoyalBlue]l--{ COVERED : 0..*\ndata.references

  DAP "data.reference" -[thickness=3,#RoyalBlue]l--{ COVERED 


}

' resources in other repos
object "**Patient** (NHI)" as Patient <<logical resource>> #SkyBlue {
  * logical id: NHI
}

object "HPI:**Organization**\nParty agreeing to privacy policy/rules" as HPI <<logical resource>> #SkyBlue {
  HPI Org Id:+ GXXNNN
}

CONSENT -d-* DAP
CONSENT -d-* RP: <color:#Black>performer**[1]**
RP "patient" -[dotted,#SkyBlue]r- Patient: >
CONSENT "<color:#Black>sourceReference" -[dashed,#Black]l- QRC: >
CONSENT "patient" -[dotted,#SkyBlue]r- Patient: >
CONSENT -[dashed,#Black]u-- HPI: <color:#Black>performer[0]\n**Reference(Organization)**
QRC -[#LightGray]-- Q: questionnaire >

  'notes
  note as N1
    Note how the RelatedPerson is a contained
    resource of the consent and also linked as an 
    **additional performer**.
  end note
 
N1 .u.. RP

$ObjectDiagramLegendWithNote("Notes","(black dashed lines) An active consent MUST reference EITHER a source QuestionnaireResponse OR an Organization as one performer")

footer "Health NZ/Te Whatu Ora.  Generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml