@startuml

!include tags-labels.puml

top to bottom direction
skinparam dpi 200
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 40
skinparam roundcorner 5
skinparam sequenceArrowThickness 2
skinparam TitleFontSize 20

' create a object with security label
' usage: $SEC_LABELLED_INSTANCE(R1,"<object name>","<label Id")
!unquoted procedure $SEC_LABELLED_INSTANCE($Alias, $displayText="",$label="")
  object "$displayText" as $Alias {
    <color:Red><&flag> <Color:Black>security label: ""<size:16><color:DarkRed>$label""
  }
!endprocedure

!unquoted procedure $DUAL_SEC_LABELLED_INSTANCE($Alias, $displayText="",$label1="",$label2="")
  object "$displayText" as $Alias {
    <color:Red><&flag> <Color:Black>security label: ""<size:16><color:DarkRed>$label1""
    <color:Red><&flag> <Color:Black>security label: ""<size:16><color:DarkRed>$label2""
  }
!endprocedure

title FHIR Consent instances for patient opted-out (of treatment / data sharing)

frame "Representation of consent denied (or withdrawn) by patient" as F {


  object "<size:16>**Consent to treatment**\n<size:16>**:CONSENT**" as TREATCONSENT #DodgerBlue {
    * status: ""<color:GreenYellow>**#ACTIVE**""
    * scope: ""**#treatment**""
    * policy: reference to regs/leg.
  }

  object "treatment provision" as TP #Brown/SandyBrown  {
    * type: ""<color:GreenYellow>**#PERMIT**""
    * period: 
      **""2023-01-21"" to ""2026-01-20""**
  }

  object "<size:16>**Consent to collect/share data**\n<size:16>**:CONSENT**" as DATACONSENT #DodgerBlue {
    * status: ""<color:GreenYellow>**#ACTIVE**""
    * scope: ""**#patient-privacy**""
    * policy: reference to regs/leg.
  }

  object "data access permit provision" as DAP #SandyBrown  {
    * type: ""<color:DarkRed>**#DENY**""
    * period: 
      ""**2023-06-23**"" to ""..""
  }

  ' resources in other repos
  object "NHI patient\n**:PATIENT**" as PATIENT <<logical reference>> #SkyBlue {
    * logical id: NHI
  }

  object "Data custodian org\n:**ORGANIZATION**" as HPI <<logical reference>> #GhostWhite {
    * HPI Org Id: ""GnXnnn""
  }

  frame "<size:12>Patient data covered by data access provision<sup>3</sup>" as COVERED #LightGreen {
    $TAGGED_INSTANCE(R1,"planned appointments, etc.\n<size:14>**:CAREPLAN**"                    ,"#rf-nz")
    $TAGGED_INSTANCE(R2,"condition severity and specifics\n<size:14>**:CONDITION**"             ,"#rf-nz")
    $TAGGED_INSTANCE(R3,"appointments\n<size:14>**:ENCOUNTER**                               "  ,"#rf-nz")
    $TAGGED_INSTANCE(R4,"preferences, health assessments\n<size:14>**:QUESTIONNAIRERESPONSE**"  ,"#rf-nz")
    $TAGGED_INSTANCE(R5,"diagnosis detail\n<size:14>**:OBSERVATION**                         "  ,"#rf-nz")

    R3 -[hidden]u- R1
    R4 -[hidden]u- R2
    R5 -[hidden]u- R4
  }
}
' positioning
TREATCONSENT -[hidden]d- TP
TP -[hidden]d- DATACONSENT

' connectors
DAP ".data.reference" -[thickness=3,#RoyalBlue]--{ COVERED 

TREATCONSENT ".patient<sup>2</sup>" -[dotted,#SkyBlue,norank]-> PATIENT
TREATCONSENT -[norank]-* TP : "".provision""
TREATCONSENT ".organization\n**HPI org. ref**<sup>1</sup>" -[dashed,#Black]l-> HPI

DATACONSENT ".patient" -[dotted,#SkyBlue,norank]-> PATIENT
DATACONSENT -d-* DAP : "".provision""
DATACONSENT ".organization\n**HPI org. ref**<sup>1</sup>" -[dashed,#Black,norank]--> HPI

legend bottom
  **Notes**
  1. ""Consent.organization"" identifies which org is custodian of the patient data.
  2. Consent instances identify the data subject in "".patient"" references.
  3. FHIR resource instances with patient data tagged for access scoping eg. #rf-nz for rheumatic fever
  4. FHIR API access rules for instances covered by an **opt-out** consents will be 
    controlled by OAUTH scopes TBD
endlegend

footer "Health NZ/Te Whatu Ora.  FHIR data model generated on %date('dd/MM/yyyy')"

@enduml