@startuml
actor AdminPractitioner
participant "Practitioner View" as PV
participant "Shared Care FHIR Server" as FHIR
participant "Queue" as MQ
participant "Common Messaging Service" as CMS
actor Patient
participant "Alphero App" as App
participant "Education Content Bucket" as ECB

== Patient Onboarding ==

== Inital Encounter ==
PV -> FHIR : POST Condition 
PV -> FHIR : POST Encounter
PV -> FHIR : POST Consent

== Create CarePlan ==
PV -> FHIR : Search Plan Definitions
PV -> FHIR : Apply Plan Definition, with patient, practitioner, and encounter
PV -> FHIR : POST CarePlan
PV -> FHIR : PUT Consent, attaching CarePlan

== Add Service Requests ==
PV -> FHIR : Search Activity Definitions
PV -> FHIR : Apply Action Definition, with patient, practitioner, and CarePlan
PV -> FHIR : POST Service Request
PV -> FHIR : PUT Consent, attaching Service Request
PV -> FHIR : PUT CarePlan, attaching Service Request

== Add Task ==
PV -> FHIR : POST Task
PV -> FHIR : PUT Consent, attaching Task
PV -> FHIR : PUT CarePlan, attaching Task

== Patient Notification via CMS ==

PV -> FHIR : POST CommunicationRequest
PV -> FHIR : PUT CarePlan, attaching CommunicationRequest
FHIR -> FHIR : Handle incoming Communication Request
FHIR -> MQ : PUT Communication message (via Subscription)
CMS -> MQ : Consume Communication message
CMS -> Patient : Send SMS or Email

== Observation Collection == 


== Routine Questionnaire Response Collection ==
Patient -> App : Opens App
App -> ECB : Fetches relevant Questionnaire
App -> App : Render Questionnaire
Patient -> App : Completes Questionnaire
App -> FHIR : POST QuestionnaireResponse
App -> FHIR : PUT Consent

== Educational Content Consumption ==
Patient -> App : Opens App, Selects and Consumes Education Content
App -> ECB : Fetches Education Content
App -> App : Render Content
Patient -> App : Completes Module
App -> FHIR : POST Provenance Resource (indicating completion)
App -> FHIR : PUT Task (add reference to Provenance)
Patient -> App : Complete Feedback Questionnaire
App -> FHIR : POST QuestionnaireResponse (completed)

@enduml