@startuml

participant "Shared Care FHIR Server" as FHIR
participant "Piki te Ora" as App

== Consent Rotation ==

App -> FHIR : GET Consent?patient.identifier={PatientNHI}&&_sort=-_lastUpdated&_tag=RemoteMonitoringViewable
FHIR --> App : Bundle(Consent[])  \n(sorted by lastUpdated desc)

App -> App : Select most recent Consent\nfrom returned Bundle

App -> App : Check size of Consent\n(e.g., > 10,000 lines)

alt Consent > 10,000 lines
    App -> FHIR : POST Consent\n(Create new Consent)
    FHIR --> App : 201 Created (New Consent)
end

== Add New Provisions ==
App -> FHIR : PUT Consent/{targetId}\n(Add new provisions)
FHIR --> App : 200 OK

@enduml