@startuml

class Consent {
  provision.data : Reference[]
}

class CarePlan {
  subject : Reference(Patient)
  encounter : Reference(Encounter)
}

class Encounter {
  subject : Reference(Patient)
}

class Condition {
  subject : Reference(Patient)
}

class CareTeam {
  // participants, subject, etc.
}

class ServiceRequest {
  subject : Reference(Patient)
}

Consent --> CarePlan : provision.data
Consent --> Encounter : provision.data
Consent --> Condition : provision.data
Consent --> CareTeam : provision.data
Consent --> ServiceRequest : provision.data
Consent --> Observation : provision.data
Consent --> QuestionnaireResponse : provision.data

CarePlan --> ServiceRequest: activity.reference
CarePlan --> Condition: addresses.reference
CarePlan --> Encounter : encounter.reference
CarePlan --> CareTeam : careTeam.reference

@enduml