@startuml
class Consent {
  provision.data : Reference[]
}

class CarePlan {
  subject : Reference(Patient)
  encounter : Reference(Encounter)
}

class Condition {
  subject : Reference(Patient)
}

class CareTeam {
  // participants, subject, etc.
}

class Task {
  subject : Reference(Patient)
}

class CommunicationRequest {
  subject : Reference(Patient)
}

Consent --> CarePlan : provision.data
Consent --> Encounter : provision.data
Consent --> Condition : provision.data
Consent --> CareTeam : provision.data
Consent --> ServiceRequest : provision.data
Consent --> Observation : provision.data
Consent --> QuestionnaireResponse : provision.data

CarePlan --> Condition: addresses.reference
CarePlan --> Encounter : encounter.reference
CarePlan --> CareTeam : careTeam.reference
CarePlan --> CommunicationRequest : activity.reference
CarePlan --> Task : activity.reference

@enduml