@startuml seq-SF-to-FHIR-integration


autonumber "<b> 00"

skinparam ArrowFontSize 16
skinparam BoxPadding 10
skinparam dpi 400
skinparam MaxMessageSize 350
skinparam NoteFontSize 11
skinparam ParticipantPadding 5
skinparam responseMessageBelowArrow true
skinparam roundcorner 15
skinparam sequenceArrowThickness 2
skinparam SequenceMessageAlignment left
skinparam ArrowFontSize 12
skinparam sequenceStyle uml2
skinparam sequencegroupfontsize 14
' semi-transparent sequence groups!
' see https://sarafian.github.io/tips/2021/03/11/plantuml-tips-tricks-1.html#:~:text=responseMessageBelowArrow-,Semi,-transparent%20group%20backgrounds
skinparam SequenceGroupBodyBackgroundColor #EEEEFF50


scale max 500 width


'' ** page 1
title "Rheumatic Fever: Salesforce Health Cloud patient registration integration to Te Whatu Ora FHIR"

actor "RF Service user" as USER
participant "Salesforce\nHealth Cloud" as OLLIE #YellowGreen
participant "Integration\n Error\nMonitor\n (DATADOG or SF)" as WATCHDOG #IndianRed
entity "Salesforce API" as ROSIE #YellowGreen
participant "Mulesoft" as TILLY #SkyBlue

box "TWO FHIR Shared Care API" #LightGrey
  entity "NIA OAUTH service" as WICKET
  entity "**Patient FHIR API**\n(Rheumatic fever profile)" as PATIENT #LightSalmon
  database "AWS DynamoDB/\nOpensearch" as REPO #Orange 
end box

autonumber stop

?-> TILLY: init
TILLY -> WICKET++: OAUTH2.0 Client Credentials Flow(\n\t1. api-key\n\t2. service provider's client credentials) 
return OAUTH token

USER -> OLLIE++ #YellowGreen: Patient registration\ndata entry completed
OLLIE -/ TILLY++ #SkyBlue: <color:red>PATIENT-CHANGE (platform event)
deactivate OLLIE

TILLY -> OLLIE: Retrieve Patient data \n<size:10>(Salesforce REST API composite request)
TILLY -> PATIENT++: ""GET /Patient?""\n""identifier=https://standards.digital.health.nz/ns/nhi-id|{{NHI}}&""\n""_profile={{RF Patient profile}}""

PATIENT -> REPO: search
PATIENT -> TILLY--: ""200 OK"" Searchset Bundle

alt No existing Patient
  TILLY -> TILLY: Form FHIR Patient payload\n from Salesforce H/C data
  TILLY -> PATIENT++: ""POST /Patient""
  PATIENT -> REPO: create new instance
  PATIENT -> TILLY--: ""201 CREATED"" - instance representation
  TILLY -/ WATCHDOG: <color:red>CREATED PATIENT (platform event?)

else Existing matching Patient

  TILLY -> TILLY: **Replace FHIR Patient payload**\n with data from Salesforce H/C
  TILLY -> PATIENT++: ""PUT //Patient/{{existing id}}""
  PATIENT -> REPO: update existing instance
  PATIENT -> TILLY--: ""200 OK"" - instance representation
  TILLY -/ WATCHDOG: <color:red>UPDATED PATIENT (platform event?)
end


' *******************
' ** page 2
'newpage Rheumatic Fever: HNZ FHIR updates to Salesforce Health Cloud


@enduml