Instance: HSAAP Adjudicated Claim Response
InstanceOf: ClaimResponse
Usage: #example
* identifier.system = "https://api.messaging.digital.health.nz/fileID"
* identifier.value = "7612345"
* status = #active
* type = $HeaderRecordType#ExampleRecordType
* use = #claim
* patient.identifier.use = #official
* patient.identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* patient.identifier.value = "ZXP7823"
* patient.display = "Carey Carrington"
* created = "2014-08-16"
* insurer.identifier.system = "http://www.jurisdiction.org/insurers"
* insurer.identifier.value = "555123"
* request = Reference(Claim/790423052393482)
* outcome = #complete
* item.itemSequence = 1
* item.adjudication[0].category.coding.code = #eligible
* item.adjudication[=].amount.value = 235.4
* item.adjudication[=].amount.currency = #NZD
* item.adjudication[+].category.coding.code = #copay
* item.adjudication[=].amount.value = 20
* item.adjudication[=].amount.currency = #NZD
* item.adjudication[+].category.coding.code = #eligpercent
* item.adjudication[=].value = 80
* item.adjudication[+].category.coding.code = #benefit
* item.adjudication[=].amount.value = 172.32
* item.adjudication[=].amount.currency = #NZD
* item.detail[0].detailSequence = 1
* item.detail[=].noteNumber = 1
* item.detail[=].adjudication.category.coding.code = #eligible
* item.detail[=].adjudication.amount.value = 100
* item.detail[=].adjudication.amount.currency = #NZD
* item.detail[+].detailSequence = 2
* item.detail[=].adjudication.category.coding.code = #eligible
* item.detail[=].adjudication.amount.value = 110
* item.detail[=].adjudication.amount.currency = #NZD
* item.detail[+].detailSequence = 3
* item.detail[=].adjudication.category.coding.code = #eligible
* item.detail[=].adjudication.amount.value = 200
* item.detail[=].adjudication.amount.currency = #NZD
* total[0].category.coding.code = #submitted
* total[=].amount.value = 460
* total[=].amount.currency = #NZD
* total[+].category.coding.code = #benefit
* total[=].amount.value = 382.32
* total[=].amount.currency = #NZD
* payment.type = $ex-paymenttype#complete
* payment.date = "2014-08-31"
* payment.amount.value = 382.32
* payment.amount.currency = #NZD