{
  "openapi": "3.0.3",
  "info": {
    "version": "0.4.0",
    "title": "Health NZ | Te Whatu Ora Shared Care FHIR API",
    "description": "Health NZ | Te Whatu Ora Shared Care FHIR API",
    "license": {
      "name": "TBC",
      "url": "https://licence.example.org"
    },
    "contact": {
      "name": "Health New Zealand Te Whatu Ora",
      "url": "https://www.tewhatuora.govt.nz"
    }
  },
  "servers": [
    {
      "url": "https://fhir.ap1.digital.health.nz/R4",
      "description": "Health NZ | Te Whatu Ora Shared Care FHIR API"
    }
  ],
  "paths": {
    "/": {
      "post": {
        "summary": "System level interactions",
        "description": "System level interactions",
        "tags": [
          "system"
        ],
        "operationId": "systemInteractions"
      }
    },
    "/Bundle/{rid}": {
      "get": {
        "summary": "Read Bundle",
        "description": "Read Bundle",
        "tags": [
          "Bundle"
        ],
        "operationId": "readBundle",
        "security": [
          {
            "smartOnFhir": [
              "system/Bundle.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Bundle",
        "description": "Delete Bundle",
        "tags": [
          "Bundle"
        ],
        "operationId": "deleteBundle",
        "security": [
          {
            "smartOnFhir": [
              "system/Bundle.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Bundle",
        "description": "Update Bundle",
        "tags": [
          "Bundle"
        ],
        "operationId": "updateBundle",
        "security": [
          {
            "smartOnFhir": [
              "system/Bundle.u"
            ]
          }
        ]
      }
    },
    "/Bundle/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Bundle (versioned)",
        "description": "Read Bundle (versioned)",
        "tags": [
          "Bundle"
        ],
        "operationId": "vreadBundle",
        "security": [
          {
            "smartOnFhir": [
              "system/Bundle.r"
            ]
          }
        ]
      }
    },
    "/Bundle": {
      "get": {
        "summary": "Search for Bundle",
        "description": "Search for Bundle",
        "tags": [
          "Bundle"
        ],
        "operationId": "searchBundle",
        "security": [
          {
            "smartOnFhir": [
              "system/Bundle.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Bundle",
        "description": "Create Bundle",
        "tags": [
          "Bundle"
        ],
        "operationId": "createBundle",
        "security": [
          {
            "smartOnFhir": [
              "system/Bundle.c"
            ]
          }
        ]
      }
    },
    "/CarePlan/{rid}": {
      "get": {
        "summary": "Read CarePlan",
        "description": "Read CarePlan",
        "tags": [
          "CarePlan"
        ],
        "operationId": "readCarePlan",
        "security": [
          {
            "smartOnFhir": [
              "system/CarePlan.r"
            ]
          }
        ]
      }
    },
    "/CarePlan/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read CarePlan (versioned)",
        "description": "Read CarePlan (versioned)",
        "tags": [
          "CarePlan"
        ],
        "operationId": "vreadCarePlan",
        "security": [
          {
            "smartOnFhir": [
              "system/CarePlan.r"
            ]
          }
        ]
      }
    },
    "/CarePlan": {
      "get": {
        "summary": "Search for CarePlan",
        "description": "Search for CarePlan",
        "tags": [
          "CarePlan"
        ],
        "operationId": "searchCarePlan",
        "security": [
          {
            "smartOnFhir": [
              "system/CarePlan.s"
            ]
          }
        ]
      }
    },
    "/Condition/{rid}": {
      "get": {
        "summary": "Read Condition",
        "description": "Read Condition",
        "tags": [
          "Condition"
        ],
        "operationId": "readCondition",
        "security": [
          {
            "smartOnFhir": [
              "system/Condition.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Condition",
        "description": "Delete Condition",
        "tags": [
          "Condition"
        ],
        "operationId": "deleteCondition",
        "security": [
          {
            "smartOnFhir": [
              "system/Condition.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Condition",
        "description": "Update Condition",
        "tags": [
          "Condition"
        ],
        "operationId": "updateCondition",
        "security": [
          {
            "smartOnFhir": [
              "system/Condition.u"
            ]
          }
        ]
      }
    },
    "/Condition/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Condition (versioned)",
        "description": "Read Condition (versioned)",
        "tags": [
          "Condition"
        ],
        "operationId": "vreadCondition",
        "security": [
          {
            "smartOnFhir": [
              "system/Condition.r"
            ]
          }
        ]
      }
    },
    "/Condition": {
      "get": {
        "summary": "Search for Condition",
        "description": "Search for Condition",
        "tags": [
          "Condition"
        ],
        "operationId": "searchCondition",
        "security": [
          {
            "smartOnFhir": [
              "system/Condition.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Condition",
        "description": "Create Condition",
        "tags": [
          "Condition"
        ],
        "operationId": "createCondition",
        "security": [
          {
            "smartOnFhir": [
              "system/Condition.c"
            ]
          }
        ]
      }
    },
    "/Consent/{rid}": {
      "get": {
        "summary": "Read Consent",
        "description": "Read Consent",
        "tags": [
          "Consent"
        ],
        "operationId": "readConsent",
        "security": [
          {
            "smartOnFhir": [
              "system/Consent.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Consent",
        "description": "Delete Consent",
        "tags": [
          "Consent"
        ],
        "operationId": "deleteConsent",
        "security": [
          {
            "smartOnFhir": [
              "system/Consent.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Consent",
        "description": "Update Consent",
        "tags": [
          "Consent"
        ],
        "operationId": "updateConsent",
        "security": [
          {
            "smartOnFhir": [
              "system/Consent.u"
            ]
          }
        ]
      }
    },
    "/Consent/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Consent (versioned)",
        "description": "Read Consent (versioned)",
        "tags": [
          "Consent"
        ],
        "operationId": "vreadConsent",
        "security": [
          {
            "smartOnFhir": [
              "system/Consent.r"
            ]
          }
        ]
      }
    },
    "/Consent": {
      "get": {
        "summary": "Search for Consent",
        "description": "Search for Consent",
        "tags": [
          "Consent"
        ],
        "operationId": "searchConsent",
        "security": [
          {
            "smartOnFhir": [
              "system/Consent.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Consent",
        "description": "Create Consent",
        "tags": [
          "Consent"
        ],
        "operationId": "createConsent",
        "security": [
          {
            "smartOnFhir": [
              "system/Consent.c"
            ]
          }
        ]
      }
    },
    "/Encounter/{rid}": {
      "get": {
        "summary": "Read Encounter",
        "description": "Read Encounter",
        "tags": [
          "Encounter"
        ],
        "operationId": "readEncounter",
        "security": [
          {
            "smartOnFhir": [
              "system/Encounter.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Encounter",
        "description": "Delete Encounter",
        "tags": [
          "Encounter"
        ],
        "operationId": "deleteEncounter",
        "security": [
          {
            "smartOnFhir": [
              "system/Encounter.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Encounter",
        "description": "Update Encounter",
        "tags": [
          "Encounter"
        ],
        "operationId": "updateEncounter",
        "security": [
          {
            "smartOnFhir": [
              "system/Encounter.u"
            ]
          }
        ]
      }
    },
    "/Encounter/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Encounter (versioned)",
        "description": "Read Encounter (versioned)",
        "tags": [
          "Encounter"
        ],
        "operationId": "vreadEncounter",
        "security": [
          {
            "smartOnFhir": [
              "system/Encounter.r"
            ]
          }
        ]
      }
    },
    "/Encounter": {
      "get": {
        "summary": "Search for Encounter",
        "description": "Search for Encounter",
        "tags": [
          "Encounter"
        ],
        "operationId": "searchEncounter",
        "security": [
          {
            "smartOnFhir": [
              "system/Encounter.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Encounter",
        "description": "Create Encounter",
        "tags": [
          "Encounter"
        ],
        "operationId": "createEncounter",
        "security": [
          {
            "smartOnFhir": [
              "system/Encounter.c"
            ]
          }
        ]
      }
    },
    "/Observation/{rid}": {
      "get": {
        "summary": "Read Observation",
        "description": "Read Observation",
        "tags": [
          "Observation"
        ],
        "operationId": "readObservation",
        "security": [
          {
            "smartOnFhir": [
              "system/Observation.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Observation",
        "description": "Delete Observation",
        "tags": [
          "Observation"
        ],
        "operationId": "deleteObservation",
        "security": [
          {
            "smartOnFhir": [
              "system/Observation.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Observation",
        "description": "Update Observation",
        "tags": [
          "Observation"
        ],
        "operationId": "updateObservation",
        "security": [
          {
            "smartOnFhir": [
              "system/Observation.u"
            ]
          }
        ]
      }
    },
    "/Observation/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Observation (versioned)",
        "description": "Read Observation (versioned)",
        "tags": [
          "Observation"
        ],
        "operationId": "vreadObservation",
        "security": [
          {
            "smartOnFhir": [
              "system/Observation.r"
            ]
          }
        ]
      }
    },
    "/Observation": {
      "get": {
        "summary": "Search for Observation",
        "description": "Search for Observation",
        "tags": [
          "Observation"
        ],
        "operationId": "searchObservation",
        "security": [
          {
            "smartOnFhir": [
              "system/Observation.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Observation",
        "description": "Create Observation",
        "tags": [
          "Observation"
        ],
        "operationId": "createObservation",
        "security": [
          {
            "smartOnFhir": [
              "system/Observation.c"
            ]
          }
        ]
      }
    },
    "/Person/{rid}": {
      "get": {
        "summary": "Read Person",
        "description": "Read Person",
        "tags": [
          "Person"
        ],
        "operationId": "readPerson",
        "security": [
          {
            "smartOnFhir": [
              "system/Person.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete Person",
        "description": "Delete Person",
        "tags": [
          "Person"
        ],
        "operationId": "deletePerson",
        "security": [
          {
            "smartOnFhir": [
              "system/Person.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update Person",
        "description": "Update Person",
        "tags": [
          "Person"
        ],
        "operationId": "updatePerson",
        "security": [
          {
            "smartOnFhir": [
              "system/Person.u"
            ]
          }
        ]
      }
    },
    "/Person/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Person (versioned)",
        "description": "Read Person (versioned)",
        "tags": [
          "Person"
        ],
        "operationId": "vreadPerson",
        "security": [
          {
            "smartOnFhir": [
              "system/Person.r"
            ]
          }
        ]
      }
    },
    "/Person": {
      "get": {
        "summary": "Search for Person",
        "description": "Search for Person",
        "tags": [
          "Person"
        ],
        "operationId": "searchPerson",
        "security": [
          {
            "smartOnFhir": [
              "system/Person.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create Person",
        "description": "Create Person",
        "tags": [
          "Person"
        ],
        "operationId": "createPerson",
        "security": [
          {
            "smartOnFhir": [
              "system/Person.c"
            ]
          }
        ]
      }
    },
    "/PlanDefinition/{rid}": {
      "get": {
        "summary": "Read PlanDefinition",
        "description": "Read PlanDefinition",
        "tags": [
          "PlanDefinition"
        ],
        "operationId": "readPlanDefinition",
        "security": [
          {
            "smartOnFhir": [
              "system/PlanDefinition.r"
            ]
          }
        ]
      }
    },
    "/PlanDefinition/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read PlanDefinition (versioned)",
        "description": "Read PlanDefinition (versioned)",
        "tags": [
          "PlanDefinition"
        ],
        "operationId": "vreadPlanDefinition",
        "security": [
          {
            "smartOnFhir": [
              "system/PlanDefinition.r"
            ]
          }
        ]
      }
    },
    "/PlanDefinition": {
      "get": {
        "summary": "Search for PlanDefinition",
        "description": "Search for PlanDefinition",
        "tags": [
          "PlanDefinition"
        ],
        "operationId": "searchPlanDefinition",
        "security": [
          {
            "smartOnFhir": [
              "system/PlanDefinition.s"
            ]
          }
        ]
      }
    },
    "/PlanDefinition/$apply": {
      "get": {
        "summary": "CareInTheCommunityPlanDefinitionApplyOperation",
        "description": "The apply operation applies a PlanDefinition to a given context",
        "operationId": "customOperation-PlanDefinition-apply",
        "tags": [
          "PlanDefinition"
        ],
        "security": [
          {
            "smartOnFhir": [
              "https://fhir-ig.digital.health.nz/shared-care/OperationDefinition/PlanDefinition-apply"
            ]
          }
        ]
      }
    },
    "/Questionnaire/{rid}": {
      "get": {
        "summary": "Read Questionnaire",
        "description": "Read Questionnaire",
        "tags": [
          "Questionnaire"
        ],
        "operationId": "readQuestionnaire",
        "security": [
          {
            "smartOnFhir": [
              "system/Questionnaire.r"
            ]
          }
        ]
      }
    },
    "/Questionnaire/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read Questionnaire (versioned)",
        "description": "Read Questionnaire (versioned)",
        "tags": [
          "Questionnaire"
        ],
        "operationId": "vreadQuestionnaire",
        "security": [
          {
            "smartOnFhir": [
              "system/Questionnaire.r"
            ]
          }
        ]
      }
    },
    "/Questionnaire": {
      "get": {
        "summary": "Search for Questionnaire",
        "description": "Search for Questionnaire",
        "tags": [
          "Questionnaire"
        ],
        "operationId": "searchQuestionnaire",
        "security": [
          {
            "smartOnFhir": [
              "system/Questionnaire.s"
            ]
          }
        ]
      }
    },
    "/QuestionnaireResponse/{rid}": {
      "get": {
        "summary": "Read QuestionnaireResponse",
        "description": "Read QuestionnaireResponse",
        "tags": [
          "QuestionnaireResponse"
        ],
        "operationId": "readQuestionnaireResponse",
        "security": [
          {
            "smartOnFhir": [
              "system/QuestionnaireResponse.r"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete QuestionnaireResponse",
        "description": "Delete QuestionnaireResponse",
        "tags": [
          "QuestionnaireResponse"
        ],
        "operationId": "deleteQuestionnaireResponse",
        "security": [
          {
            "smartOnFhir": [
              "system/QuestionnaireResponse.d"
            ]
          }
        ]
      },
      "put": {
        "summary": "Update QuestionnaireResponse",
        "description": "Update QuestionnaireResponse",
        "tags": [
          "QuestionnaireResponse"
        ],
        "operationId": "updateQuestionnaireResponse",
        "security": [
          {
            "smartOnFhir": [
              "system/QuestionnaireResponse.u"
            ]
          }
        ]
      }
    },
    "/QuestionnaireResponse/{rid}/_history/{vid}": {
      "get": {
        "summary": "Read QuestionnaireResponse (versioned)",
        "description": "Read QuestionnaireResponse (versioned)",
        "tags": [
          "QuestionnaireResponse"
        ],
        "operationId": "vreadQuestionnaireResponse",
        "security": [
          {
            "smartOnFhir": [
              "system/QuestionnaireResponse.r"
            ]
          }
        ]
      }
    },
    "/QuestionnaireResponse": {
      "get": {
        "summary": "Search for QuestionnaireResponse",
        "description": "Search for QuestionnaireResponse",
        "tags": [
          "QuestionnaireResponse"
        ],
        "operationId": "searchQuestionnaireResponse",
        "security": [
          {
            "smartOnFhir": [
              "system/QuestionnaireResponse.s"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create QuestionnaireResponse",
        "description": "Create QuestionnaireResponse",
        "tags": [
          "QuestionnaireResponse"
        ],
        "operationId": "createQuestionnaireResponse",
        "security": [
          {
            "smartOnFhir": [
              "system/QuestionnaireResponse.c"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "smartOnFhir": {
        "type": "oauth2",
        "description": "SMART-on-FHIR security scheme",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://ppd.auth.services.health.nz/realms/hnz-integration/protocol/openid-connect/token",
            "scopes": {
              "system/Bundle.r": "Bundle.r access",
              "system/Bundle.d": "Bundle.d access",
              "system/Bundle.u": "Bundle.u access",
              "system/Bundle.s": "Bundle.s access",
              "system/Bundle.c": "Bundle.c access",
              "system/CarePlan.r": "CarePlan.r access",
              "system/CarePlan.s": "CarePlan.s access",
              "system/Condition.r": "Condition.r access",
              "system/Condition.d": "Condition.d access",
              "system/Condition.u": "Condition.u access",
              "system/Condition.s": "Condition.s access",
              "system/Condition.c": "Condition.c access",
              "system/Consent.r": "Consent.r access",
              "system/Consent.d": "Consent.d access",
              "system/Consent.u": "Consent.u access",
              "system/Consent.s": "Consent.s access",
              "system/Consent.c": "Consent.c access",
              "system/Encounter.r": "Encounter.r access",
              "system/Encounter.d": "Encounter.d access",
              "system/Encounter.u": "Encounter.u access",
              "system/Encounter.s": "Encounter.s access",
              "system/Encounter.c": "Encounter.c access",
              "system/Observation.r": "Observation.r access",
              "system/Observation.d": "Observation.d access",
              "system/Observation.u": "Observation.u access",
              "system/Observation.s": "Observation.s access",
              "system/Observation.c": "Observation.c access",
              "system/Person.r": "Person.r access",
              "system/Person.d": "Person.d access",
              "system/Person.u": "Person.u access",
              "system/Person.s": "Person.s access",
              "system/Person.c": "Person.c access",
              "system/PlanDefinition.r": "PlanDefinition.r access",
              "system/PlanDefinition.s": "PlanDefinition.s access",
              "https://fhir-ig.digital.health.nz/shared-care/OperationDefinition/PlanDefinition-apply": "PlanDefinition-apply access",
              "system/Questionnaire.r": "Questionnaire.r access",
              "system/Questionnaire.s": "Questionnaire.s access",
              "system/QuestionnaireResponse.r": "QuestionnaireResponse.r access",
              "system/QuestionnaireResponse.d": "QuestionnaireResponse.d access",
              "system/QuestionnaireResponse.u": "QuestionnaireResponse.u access",
              "system/QuestionnaireResponse.s": "QuestionnaireResponse.s access",
              "system/QuestionnaireResponse.c": "QuestionnaireResponse.c access"
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Bundle",
      "description": "Operations related to Bundle FHIR resource"
    },
    {
      "name": "CarePlan",
      "description": "Operations related to CarePlan FHIR resource"
    },
    {
      "name": "Condition",
      "description": "Operations related to Condition FHIR resource"
    },
    {
      "name": "Consent",
      "description": "Operations related to Consent FHIR resource"
    },
    {
      "name": "Encounter",
      "description": "Operations related to Encounter FHIR resource"
    },
    {
      "name": "Observation",
      "description": "Operations related to Observation FHIR resource"
    },
    {
      "name": "Person",
      "description": "Operations related to Person FHIR resource"
    },
    {
      "name": "PlanDefinition",
      "description": "Operations related to PlanDefinition FHIR resource"
    },
    {
      "name": "Questionnaire",
      "description": "Operations related to Questionnaire FHIR resource"
    },
    {
      "name": "QuestionnaireResponse",
      "description": "Operations related to QuestionnaireResponse FHIR resource"
    }
  ]
}