@startuml FHIR-resources-model-cinc-observation

title "FHIR resource model - Patient Observations for Care in the Community"
footer "Middleware NZ design for Health NZ, %date('yyyy.MM.dd')"

skinparam BoxPadding 6
skinparam ParticipantPadding 1
skinparam roundcorner 5

skinparam sequenceArrowThickness 2

skinparam dpi 200

class CarePlan #LightSalmon {
    + ~~title~~ = //COVID-19 Response - Patient X//
    + status = //active//
    + period = plan start-end dates
    + Other elements as copied from PlanDefinition
    -- links to --
    + author -> HPI ref.
}

class CarePlanObsActivity <<contained>> #LightBlue {
    -- links to --
    **reference** --> ServiceRequest
}

class "ServiceRequest (patient vital signs)" as ServiceRequest  #LightSalmon {
    + ~~status~~ = //active//
    + ~~code~~ = SNOMED ref. (from ActivityDefinition)
    + Other elements copied from ActivityDefinition
    ...
    -- links to --
    + instantiatesCanonical --> ActivityDefinition
    + basedOn -> CarePlan ref.
    + performer -> Patient (or Nurse) ref.

}

class Observation #LightSalmon {
    + ~~status~~ = final
    + ~~code~~ = SNOMED code (from ServiceRequest)
    + component.value[]**
        Array of 
        {sign code, observation value} pairs
    -- links to --
    + basedOn -> ServiceRequest
    + subject -> Patient ref.
}

class ActivityDefinition <<canonical instance>> #OrangeRed {
    -- templated attributes --
    |_ identifier = ""//COVID19ObservationVitalSignsRequestTemplate//""
    |_ kind = ServiceRequest
    |_ status = active
    |_ code = SNOMED code (TBC by HNZ).
    |_ Further HNZ default elements for Activity type...    
    |_..
    -- instance operations --
    ""ServiceRequest **$apply**("" 
        ""   subject:""identifies patient,
        ""   practitioner:""identifies requesting practitioner,
        ""   CarePlan:id"" identifies careplan which will contain
        "")""
}

class PlanDefinition <<canonical instance>> #OrangeRed {
    -- templated attributes --
    |_ identifier = ""//CareplanTemplate-CitC-COVID19-CCCM//""
    |_ status = active
    |_ action[] = [HNZ default care plan activities...]
    |_ Further HNZ defaults for CarePlan type...
    |_ ..
    -- instance operations --
    ""CarePlan **$apply**(""
        ""   subject = "" <patient identifier>,
        ""   practitioner:"" <requesting practitioner identifier>,
        ""   encounter:id""  Encounter which led to this care plan 
}

class Goal <<contained>> #LightBlue

class HPIPerson <<logical resource>> #GreenYellow {
    -- resource namespace --
    https://standards.digital.health.\nnz/ns/hpi-person-id
}

class Patient <<logical resource>> #GreenYellow {
    -- resource namespace --
    https://standards.digital.health.nz/ns/nhi-id
}

class SNOMED <<codeable concept>> #MediumPurple {
    system = http://snowmed.info/sct
    code = 61746007
    display = "Taking patient vital \nsigns (procedure)"
}

' associations

PlanDefinition "1"..> CarePlan: $apply() instantiates

CarePlan *-right- "0..*" CarePlanObsActivity
CarePlan *-up- "1..*" Goal: goal
CarePlan "subject" --> Patient

CarePlan "author" --> HPIPerson
CarePlan -down-> PlanDefinition: instantiatesCanonical

ActivityDefinition "1".down.> ServiceRequest
note on link : S/Rs are instantiated (made) \nby applying ActivityDefinition

ActivityDefinition "code" --> SNOMED

CarePlanObsActivity "reference" --> "1" ServiceRequest

ServiceRequest -up-> ActivityDefinition: instantiatesCanonical
ServiceRequest "code" -right-> SNOMED

ServiceRequest "\nbasedOn" --> CarePlan 

ServiceRequest "subject" --> Patient

ServiceRequest --> HPIPerson
note on link: requester

diamond obsdia

Observation "1" --> obsdia : "performer"

obsdia "Patient-\ncollected Obs" --> Patient
obsdia "Nurse-\ncollected Obs" ..> HPIPerson
Observation "basedOn" --> ServiceRequest
Observation --> SNOMED: code

note top of Observation #Yellow {
    * Mobile app creates Observation Resource from scratch, 
        populating observation data in component.value[] array.
         (Data codes and value types to be decided by HNZ).
    
    Linkages
    * performer --> Patient (copied from S/R subject)
    * basedOn --> ServiceRequest
}

legend right
    **Notes**
    # This model uses UML Class diagram notation
    
    # FHIR Resource types and resource References are modelled as UML classes and associations
    
    # **CarePlanObsActivity** is a reference contained in a CarePlan activity.  The client inserts this into 
    the CarePlan just after creating the ServiceRequest

    # Not shown for simplicity:
        - Linkage between CarePlan, Condition and Encounter resources
        - All Consents, consent linkage and Questionnaires

    | **Class colour key** | **FHIR resource stereotype** |
    |<#LightSalmon> FHIR resource supported by this repository | local resource |
    |<#OrangeRed> Definition resource instance | definitional |
    |<#LightBlue> Resource contained in another resource (does not standalone) | contained|
    |<#mediumPurple> Reference to concept in code system | codeable concept |
    |<#GreenYellow> Logical references to a resource in another repository | logical reference |

endlegend

@enduml