Instance: AntiViralEligibilityQuestionnaireResponse
InstanceOf: QuestionnaireResponse
Description: "An example QuestionnaireResponse payload demonstrating data collected in a pharmacy eligibility review"
Usage: #example
* status = #completed
* authored = "2023-03-27T20:15:56.592Z"
* questionnaire = "https://build.fhir.org/ig/tewhatuora/cinc-fhir-ig/Questionnaire/Questionnaire-AntiViralEligibilityQuestionnaire"
* subject.type = "Patient"
* subject.identifier.use = #official
* subject.identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* subject.identifier.value = "ZXP7823"
* subject.display = "Carey Carrington"
* author.type = "Practitioner"
* author.identifier.use = #official
* author.identifier.system = "https://standards.digital.health.nz/ns/hpi-person-id"
* author.identifier.value = "99ZZFX"
* author.display = "Dottie McStuffins"
* item[0].linkId = "CurrentDate"
* item[=].text = "Current Date/Time"
* item[=].answer.valueDateTime = "2023-03-27T20:15:56.592Z"
* item[+].linkId = "ReviewDate"
* item[=].text = "Date Review Performed"
* item[=].answer.valueDate = "2023-03-27"
* item[+].linkId = "COVID19-Positive"
* item[=].text = "Is the patient a probable or confirmed COVID-19 case?"
* item[=].answer.valueCoding.display = "Yes"
* item[+].linkId = "SymptomsStart"
* item[=].text = "When did the patient's symptoms start?"
* item[=].answer.valueCoding.display = "Within the last 5 days (if considering nirmatrelvir with ritonavir or molnupiravir)"
* item[+].linkId = "supoxygen"
* item[=].text = "The patient requires supplemental oxygen"
* item[=].answer.valueCoding.display = "No"
* item[+].linkId = "criteria"
* item[=].text = "The Patient:"
* item[=].answer.valueCoding.display = "is immunocompromised* and not expected to reliably mount an adequate immune response to COVID-19 vaccination or SARS-CoV-2 infection, regardless of vaccination status"
* item[+].linkId = "eligible-yes"
* item[=].text = "Yes - the patient IS eligible for COVID-19 Antivirals"
* item[=].answer.valueCoding.display = "confirm"
* item[+].linkId = "PharmacistInformation"
* item[=].text = "Please provide pharmacist details"
* item[=].item[0].linkId = "PharmacistName"
* item[=].item[=].text = "Pharmacist Name"
* item[=].item[=].answer.valueString = "From HPI"
* item[=].item[+].linkId = "PharmacistID"
* item[=].item[=].text = "Pharmacist ID"
* item[=].item[=].answer.valueString = "From HPI"
* item[+].linkId = "PharmacyInformation"
* item[=].text = "Please provide details about the pharmacy organisation"
* item[=].item[0].linkId = "PharmacyName"
* item[=].item[=].text = "Pharmacy Name"
* item[=].item[=].answer.valueString = "From HPI"
* item[=].item[+].linkId = "PharmacyID"
* item[=].item[=].text = "Pharmacy ID"
* item[=].item[=].answer.valueString = "From HPI"
* item[=].item[+].linkId = "PharmacyAddress"
* item[=].item[=].text = "Pharmacy address details"
* item[=].item[=].answer.valueString = "FROM HPI e.g. 133 Molesworth Street, Thorndon 6011, Wellington"
// * item[=].item[+].linkId = "PharmacyAddress"
// * item[=].item[=].text = "Pharmacy address details"
// * item[=].item[=].item[0].linkId = "StreetNumberName"
// * item[=].item[=].item[=].text = "Street number + Street Name"
// * item[=].item[=].item[=].answer.valueString = "From HPI"
// * item[=].item[=].item[+].linkId = "Suburb"
// * item[=].item[=].item[=].text = "Suburb"
// * item[=].item[=].item[=].answer.valueString = "From HPI"
// * item[=].item[=].item[+].linkId = "TownCity"
// * item[=].item[=].item[=].text = "Town/City"
// * item[=].item[=].item[=].answer.valueString = "From HPI"
// * item[=].item[=].item[+].linkId = "Postcode"
// * item[=].item[=].item[=].text = "Postcode"
// * item[=].item[=].item[=].answer.valueString = "From HPI"
* item[+].linkId = "GeneralPracticeInformation"
* item[=].text = "Please provide details about the patient's general practice"
* item[=].item[0].linkId = "GPName"
* item[=].item[=].text = "General Practitioner Name"
* item[=].item[=].answer.valueString = "From HPI"
* item[=].item[+].linkId = "GPEDI"
* item[=].item[=].text = "General Practice EDI"
* item[=].item[=].answer.valueString = "From HPI"
* item[+].linkId = "SendToGP"
* item[=].text = "Send note to GP Inbox?"
* item[=].answer.valueBoolean = true