Instance: ObservationFlatExportResponse
InstanceOf: Binary
Usage: #example
Description: "Example response from invoking the Observation $flat-export operation."

* contentType = #application/json
* data = "W3siaWQiOiIxMjM0IiwiZWZmZWN0aXZlRGF0ZVRpbWUiOiIyMDI1LTA0LTIyIiwidmFsdWVRdWFudGl0eSI6eyJ2YWx1ZSI6Ni4zLCJ1bml0IjoibW1vbC9sIiwic3lzdGVtIjoiaHR0cDovL3VuaXRzb2ZtZWFzdXJlLm9yZyIsImNvZGUiOiJtbW9sL0wifX0seyJpZCI6IjU2NzgiLCJlZmZlY3RpdmVEYXRlVGltZSI6IjIwMjUtMDQtMjMiLCJ2YWx1ZVF1YW50aXR5Ijp7InZhbHVlIjoyLjMsInVuaXQiOiJtbW9sL2wiLCJzeXN0ZW0iOiJodHRwOi8vdW5pdHNvZm1lYXN1cmUub3JnIiwiY29kZSI6Im1tb2wvTCJ9fV0="
