Instance: COVIDPublicHealthHistoryQuestionnaireResponseSherrylCarrion
InstanceOf: QuestionnaireResponse
Description: "Demonstrates responses collected for COVIDPublicHealthHistoryQuestionnaire in relation to example patient Sherryl Carrion"
Usage: #example
* questionnaire = Canonical(COVIDPublicHealthHistoryQuestionnaire)
* status = #completed
* subject.type = "Patient"
* subject.identifier.use = #official
* subject.identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* subject.identifier.value = "ZXP7825"
* subject.display = "Sheryl Carrion"
* author.type = "Practitioner"
* author.identifier.use = #official
* author.identifier.system = "https://standards.digital.health.nz/ns/hpi-person-id"
* author.identifier.value = "99ZZFX"
* author.display = "Dottie McStuffins"
* authored = "2023-06-26T04:46:11.379Z"
* item.linkId = "p01"
* item.text = "Public Health History"
* item.item[0].linkId = "p01-q01-PlacesVisitedRecently"
* item.item[=].text = "Places visited in last 14 days"
* item.item[=].answer.valueString = "London, Lower Hutt, Lagos"
* item.item[+].linkId = "p01-q02-PrevPositive"
* item.item[=].text = "Previous positive COVID-19 test?"
* item.item[=].answer.valueBoolean = true

* item.item[+].linkId = "p01-q02-1-PrevPositiveMonth"
* item.item[=].text = "Month of positive COVID-19 test?"
* item.item[=].answer.valueString = "May"
* item.item[+].linkId = "p01-q02-2-PrevPositiveYear"
* item.item[=].text = "Year of positive COVID-19 test?"
* item.item[=].answer.valueDate = "2022"

* item.item[+].linkId = "p01-q03-HighSuspicionOfCOVID"
* item.item[=].text = "High suspicion of prev. COVID-19?"
* item.item[=].answer.valueBoolean = true
* item.item[+].linkId = "p01-q04-PotentialCloseContact"
* item.item[=].text = "Potential close contact with a COVID-19 positive person in the last 14 days?"
* item.item[=].answer.valueBoolean = true
* item.item[+].linkId = "p01-q05-COVID19Vaccine"
* item.item[=].text = "COVID-19 vaccine?"
* item.item[=].answer.valueCoding.display = "Full"
* item.item[+].linkId = "p01-q06-dose1-date"
* item.item[=].text = "Date"
* item.item[=].answer.valueDate = "2022-03-01"
* item.item[+].linkId = "p01-q06-dose1-vaccine"
* item.item[=].text = "Vaccine given"
* item.item[=].answer.valueCoding = #208 "Pfizer/BioNtech"
* item.item[+].linkId = "p01-q06-dose1-country"
* item.item[=].text = "Country where vaccinated"
* item.item[=].answer.valueCoding = urn:iso:std:iso:3166#NZ "New Zealand"
* item.item[+].linkId = "p01-q06-dose2-date"
* item.item[=].text = "Date"
* item.item[=].answer.valueDate = "2022-06-03"
* item.item[+].linkId = "p01-q06-dose2-vaccine"
* item.item[=].text = "Vaccine given"
* item.item[=].answer.valueCoding = #207 "Moderna"
* item.item[+].linkId = "p01-q06-dose2-country"
* item.item[=].text = "Country where vaccinated"
* item.item[=].answer.valueCoding = urn:iso:std:iso:3166#NG "Nigeria"
* item.item[+].linkId = "p01-q06-dose3-date"
* item.item[=].text = "Date"
* item.item[=].answer.valueDate = "2022-09-30"
* item.item[+].linkId = "p01-q06-dose3-vaccine"
* item.item[=].text = "Vaccine given"
* item.item[=].answer.valueCoding = #210 "AstraZeneca / Covishield"
* item.item[+].linkId = "p01-q06-dose3-country"
* item.item[=].text = "Country where vaccinated"
* item.item[=].answer.valueCoding = urn:iso:std:iso:3166#GB "United Kingdom of Great Britain and Northern Ireland"