Instance: GenomeSequencingRequestQuestionnaireResponse
InstanceOf: QuestionnaireResponse
Description: "An example QuestionnaireResponse payload demonstrating data collected for a genome sequencing request."
Usage: #example
* status = #completed
* authored = "2023-07-06T03:18:06.523Z"
* questionnaire = "https://build.fhir.org/ig/tewhatuora/cinc-fhir-ig/Questionnaire-GenomeSequencingRequest"
* item[0].linkId = "p02"
* item[=].text = "Patient Information"
* item[=].item[0].linkId = "p02-q01-PostMortem"
* item[=].item[=].text = "Is the patient post mortem?"
* item[=].item[=].answer.valueCoding.display = "Yes, patient is post mortem"
* item[=].item[+].linkId = "p02-q02-Traveled"
* item[=].item[=].text = "Has the patient traveled in the last 14 days?"
* item[=].item[=].answer.valueCoding.display = "Yes, patient has traveled in the last 14 days"
* item[=].item[+].linkId = "p02-q03-MedicalConditions"
* item[=].item[=].text = "Does the patient have any underlying medical conditions?"
* item[=].item[=].answer.valueCoding.display = "Yes, patient has underlying conditions"
* item[=].item[+].linkId = "p02-q03.1-MedicalConditions.Details"
* item[=].item[=].text = "Condition details"
* item[=].item[=].answer.valueCoding.display = "SNOMED1"
* item[=].item[+].linkId = "p02-q03.2-MedicalConditions.Other"
* item[=].item[=].text = "Symptoms/Other detail"
* item[=].item[=].answer.valueString = "Other symptoms"
* item[=].item[+].linkId = "p02-q04-ImmunosuppressiveDrugs"
* item[=].item[=].text = "Is the patient receiving immunosuppressive drugs?"
* item[=].item[=].answer.valueCoding.display = "Yes, patient is receiving immunosuppressive drugs"
* item[=].item[+].linkId = "p02-q04.1-MedicationName"
* item[=].item[=].text = "Medication name"
* item[=].item[=].answer.valueString = "Some medication"
* item[=].item[+].linkId = "p02-q04.2-MedicationStart"
* item[=].item[=].text = "When did they start their medication?"
* item[=].item[=].answer.valueDate = "2023-06-26"
* item[=].item[+].linkId = "p02-q05-AntiVirals"
* item[=].item[=].text = "Is the patient receiving antivirals?"
* item[=].item[=].answer.valueCoding.display = "Yes, patient is receiving antivirals"
* item[=].item[+].linkId = "p02-q06-MonoclonalAntibodies"
* item[=].item[=].text = "Is the patient receiving monoclonal antibodies?"
* item[=].item[=].answer.valueCoding.display = "Yes, patient is receiving monoclonal antibodies"
* item[=].item[+].linkId = "p02-q07-OtherBloodProducts"
* item[=].item[=].text = "Other blood products:"
* item[=].item[=].answer.valueCoding.display = "Yes, patient is receiving other blood products"
* item[+].linkId = "p03"
* item[=].text = "Sample Information"
* item[=].item[0].linkId = "p03-q01-SampleDate"
* item[=].item[=].text = "Date sample was collected"
* item[=].item[=].answer.valueDate = "2023-07-06"
* item[=].item[+].linkId = "p03-q02-SampleType"
* item[=].item[=].text = "Sample type"
* item[=].item[=].answer.valueCoding.display = "Viral Swab"
* item[=].item[+].linkId = "p03-q03-SampleSite"
* item[=].item[=].text = "Sample site"
* item[=].item[=].answer.valueString = "Mouth"
* item[=].item[+].linkId = "p03-q04-AlreadySent"
* item[=].item[=].text = "Has the sample already been sent to ESR?"
* item[=].item[=].answer.valueCoding.display = "Yes, sample has been sent to ESR"
* item[=].item[+].linkId = "p03-q04.1-SentDate"
* item[=].item[=].text = "Date sample was sent to ESR"
* item[=].item[=].answer.valueDate = "2023-07-05"
* item[=].item[+].linkId = "p03-q05-ImageLabel"
* item[=].item[=].text = "Image label"
* item[=].item[=].answer.valueString = "Some Label"
* item[=].item[+].linkId = "p03-q06-ImageUpload"
* item[=].item[=].text = "Upload image"
* item[=].item[=].answer.valueAttachment.title = "barcode.png"
* item[=].item[=].answer.valueAttachment.contentType = #image/png
* item[=].item[=].answer.valueAttachment.creation = "2023-07-06T02:31:26.538Z"
* item[=].item[=].answer.valueAttachment.data = "iVBORw0KGgoAAAANSUhEUgAAARMAAAC3CAMAAAAGjUrGAAAAflBMVEX///8AAAABAQH7+/u3t7dRUVHn5+dwcHCEhISlpaXOzs67u7uRkZE1NTX4+Ph4eHiZmZnf39/W1tYpKSkuLi5fX1/BwcFMTEzZ2dmrq6siIiISEhKgoKBXV1fr6+vq6upra2sbGxvIyMiIiIhCQkINDQ05OTl/f39lZWUXFxdxMDsmAAAHB0lEQVR4nO2d63LiOBCF1RGxwYBswOCYBONw5/1fcLt1syHMzm5tmNmaOqdqQNal1frcujA/IqUgCIIgCIIgCIIgCIIgCIIgCIIgCIIgCIIgCIIgCIL+VOn/lZnfL303En33fZPsZ+q7jPsn/aX4Z548MOKffjVtnea6SfecytI8H3D/dTvnp33aKGU4a6hm/CkaqDrN1CRNpJ3JQ9HI2qnbTBVcdHZ1zypJC5W1tRqnK1vBttN5yskkndisldRM52rS2iKRODJPR2rFhnfSiis0UnTWCWcV0ip1jjxRRDqhkhNjIhJfU5JBLIj9NJy1Vhk5TVROA3WguWXCGZ+2KLVmhlz0ykXvvrKaU6UGNFQFfdgKB5rxwLlAqTcuEn3YmuNYZHsTR1o14nTN6Yq/E2UNzvhjw1kjduTMvT2bydS68mKZ5JbJVJiIn6UM/IVFBbsyZi/fApNFj8mevdwwk7Wr+85MNsxkz0xcIFV9Jq+eiVQdxyJ+kJezYpMjdkaYvFomL8QGZ5y19EyGYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYAImYPLbmAy4e7mGIGUvlbqS/5v/R7Ujpz0XDdSp+5v/ZJlcrBm5DqCiTPm6FJlMqLAVpjJwY5nM6WCzCltTTL55gzx0eTkXex2AsDzw96z7m//VL2Zikmbb8HeTGP7cyg0QOtk2jRSIEqPdP3tXht4220SHNtxqa2zLbePkmQy5tXEVEmmWOLOujZHKtp0UuZbOES7aSjvN5rk/6wb3aNv9SiZR/vqPr9eJPLxYpMu6vTYkMPkbPbw25GvW3UUiv4XJz/WTi05scZg736Nej09iMt9ls5C+Y2IaE5JNtktCMsyI4GKsZVyB7hlwtW6Y+Fqhlcl2sX/pprM73/VKbp3JvDNPYTK3q9nJO9JjwgOrKfSWbKRWtfWV/Mrp1fnk7kahOBBeCTPfS49J5duf7NNeklPXROfycHFjd6t5Zbw3bHvnrcr+Q0vr8lOYTGlYj9ow1W/iRLwdu2RNp0ld+VHkaZ6fS7r6ao29E8aqoCWXLcObbt49klsmRSoWKrdHDeizqJd221WqpenH6EStfVjTpOYSdzsP7/yRyYgORX1yV9Q8g0lid3n1vnCPfSYplXlgsrLfB3caEe2ih/FOHSUR04t1pU+08skH68nBGTjbOiU11hlxQ5ey83OM5Uo2ZUdrSVUaAI9tw7Xt6xlMdu7AUJF7t30mi4MuAhOnc/BKriwKSX2kOM9zarraeuMPaOoRk6UPzZHkJrTW1qqt4XodO9RTZ51f3Z5urmO62KPRM5jUzu/WvWA+PprIZBK8C9oew5BXgsSvpCMb3doP9Frmc/8wodOg9nEz58PqzV68d/HJgXCgfPDu+lkJE80NZYwfbqSvrs+JBGHHRMtSFc4n331PU20PzTxPHJNTZbanSyy9YcLT5eyTfKAs9z46rtSY1dylq8/pgvxRtXELqePwNs3VqiyirYxK31xrOZ26OZbQlcfZrO3gfd9LCtvduR8nY3e1lhqcPlQxXanv1MgxabuVoq/IRCuTdkjUYFQs/M+UAefOqcOo5kd33udNa5/V7ofKF03JU1T6wntLWJxSOk6KNdnpUsjb14+ZmKWQ//Ep77+pDkxmj0q7ODELWtzerlY5F0vachynN43sdMxtvLz5vepWGTfwQ8lpY+St221en/1vKRXnzsaVqD6T5Eqnh/5+jwYu0i/xbdyoY3Kg9O6I7Wg2dE3bVyqXnY/e5JIx8wm/JPVVeRye4Z+VSgB8OKvNjNcqI13VjskhLtsdk0UXsc9Q5syfur2jr8gk8z9enSydiWWyDQe4Loha18iPmx4xOcTuGhdHu7AnaQ5IN492bsFYx/aRySqsz09SYwdr+PPRtIxMCuotY2OpOicXWo0xJuOjZ2w+oasdcE2v2p7iHtj9jAPVjuYybtsHv0SzZ7JgJf72QNVjMoyL0ZPER8j08tmdJG4UmQxpXS4Wi6vFwOfq9hS2F9FbWE+GF14uF34aTeldqj2a+NcueCa8xLZHOtoZYkxlT2pWfGxOLy/dPnsOp8SWFqL1w9D+DjUX+c+bH/xi/QjhMTl+ilxojGT33PQCZxYGcqKXTdxnTH5keg/XwvKlS9cl0UvrljO97BZfteXNhT4nsWI8s+VX68z705goCf9/28L8oMl99j+zbLpfwvclzxz2N+u33sT7x1wDDEEQBEEQBEEQBEEQBEEQBEEQBEEQBEEQBEF/iP4CfnmmbUrwxC8AAAAASUVORK5CYII="
* item[+].linkId = "p04"
* item[=].text = "Sample transport information"
* item[=].item[0].linkId = "p04-q01-SampleStoredState"
* item[=].item[=].text = "What state was the sample stored in?"
* item[=].item[=].answer.valueCoding.display = "Ambient"
* item[=].item[+].linkId = "p04-q02-SampleTransportedState"
* item[=].item[=].text = "What state was the sample transported in?"
* item[=].item[=].answer.valueCoding.display = "Ambient"
* item[=].item[+].linkId = "p04-q03-SampleStorageDateTime"
* item[=].item[=].text = "Date and time stored"
* item[=].item[=].answer.valueDateTime = "2023-07-06T03:16:15.887Z"
* item[=].item[+].linkId = "p04-q04-SampleUrgency"
* item[=].item[=].text = "Sample urgency"
* item[=].item[=].answer.valueCoding.display = "Priority"
* item[=].item[+].linkId = "p04-q05-SampleTransportMedium"
* item[=].item[=].text = "Transport medium"
* item[=].item[=].answer.valueString = "Frozen"
* item[+].linkId = "p05"
* item[=].text = "Clinical information"
* item[=].item[0].linkId = "p05-q01-OtherLabNumbers"
* item[=].item[=].text = "Other lab numbers associated with this case"
* item[=].item[=].answer.valueString = "12345"
* item[=].item[+].linkId = "p05-q02-PCRDate"
* item[=].item[=].text = "Date of PCR test"
* item[=].item[=].answer.valueDate = "2023-07-06"
* item[=].item[+].linkId = "p05-q03-CTValue"
* item[=].item[=].text = "CT value"
* item[=].item[=].answer.valueString = "12345"
* item[=].item[+].linkId = "p05-q04-AntibodyTestingResults"
* item[=].item[=].text = "Antibody testing results"
* item[=].item[=].answer.valueString = "??"
* item[+].linkId = "p06"
* item[=].text = "Diagnostic services requested"
* item[=].item[0].linkId = "p06-q01-Services"
* item[=].item[=].text = "Which diagnostic services have been requested?"
* item[=].item[=].answer[0].valueCoding.display = "Viral lineage"
* item[=].item[=].answer[+].valueCoding.display = "Genomic variation"
* item[=].item[=].answer[+].valueCoding.display = "Coinfection or reinfection with a different virus variant"
* item[=].item[=].answer[+].valueCoding.display = "Remdesivir or Nirmatrelvir drug resistance"
* item[=].item[=].answer[+].valueCoding.display = "Virus susceptibility "
* item[=].item[+].linkId = "p06-q02-OtherServices"
* item[=].item[=].text = "Have any other diagnostic services been requested?"
* item[=].item[=].answer.valueCoding.display = "Yes, other diagnostic services have been requested"
* item[=].item[+].linkId = "p06-q02.1-OtherServicesRequested"
* item[=].item[=].text = "Other diagnostic services requested"
* item[=].item[=].answer.valueString = "Some other service"
* item[+].linkId = "p07"
* item[=].text = "Details for reporting"
* item[=].item[0].linkId = "p07-q01-HPI"
* item[=].item[=].text = "Requestor HPI "
* item[=].item[=].answer.valueString = "HPI1234"
* item[=].item[+].linkId = "p07-q02-HPIFacility"
* item[=].item[=].text = "HPI Facility Code"
* item[=].item[=].answer.valueString = "HPI5678"
* item[=].item[+].linkId = "p07-q03-FirstName"
* item[=].item[=].text = "First name"
* item[=].item[=].answer.valueString = "Carey"
* item[=].item[+].linkId = "p07-q04-LastName"
* item[=].item[=].text = "Last name"
* item[=].item[=].answer.valueString = "Carrington"
* item[=].item[+].linkId = "p07-q05-Email"
* item[=].item[=].text = "Email"
* item[=].item[=].answer.valueString = "carey.carrington@somelab.com"
* item[=].item[+].linkId = "p07-q06-LabPhone"
* item[=].item[=].text = "Lab phone number"
* item[=].item[=].answer.valueString = "12345678"
* item[=].item[+].linkId = "p07-q07-TechnicianPhone"
* item[=].item[=].text = "Technician phone number"
* item[=].item[=].answer.valueString = "98765432"